import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Sourabh
 */
public class Agent_page extends javax.swing.JFrame {
String name1;
    /**
     * Creates new form ap
     */
    public Agent_page() {   
        initComponents();
    }
       public Agent_page(String log) {
         name1=log;   
         initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footer_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b8 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        jlbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHOPIFY MOBILES");
        setMaximumSize(new java.awt.Dimension(1366, 725));
        setMinimumSize(new java.awt.Dimension(1366, 725));
        setPreferredSize(new java.awt.Dimension(1366, 725));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footer_lbl.setBackground(new java.awt.Color(0, 0, 0));
        footer_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        footer_lbl.setForeground(new java.awt.Color(255, 255, 255));
        footer_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer_lbl.setText("   Copyright © SASOFTECH TECHNOLOGY SOLUTIONS. All rights reserved.");
        footer_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        footer_lbl.setMaximumSize(new java.awt.Dimension(1366, 17));
        footer_lbl.setMinimumSize(new java.awt.Dimension(1366, 17));
        footer_lbl.setOpaque(true);
        footer_lbl.setPreferredSize(new java.awt.Dimension(1366, 17));
        getContentPane().add(footer_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                            shopping  habits  sorted  out  .....");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 490, 60));

        b8.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        b8.setForeground(new java.awt.Color(204, 204, 204));
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about_but.png"))); // NOI18N
        b8.setText("CUSTOMER MANAGEMENT");
        b8.setBorderPainted(false);
        b8.setContentAreaFilled(false);
        b8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b8.setIconTextGap(2);
        b8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b8MouseExited(evt);
            }
        });
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 300, 140));

        b11.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        b11.setForeground(new java.awt.Color(204, 204, 204));
        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blog_but.png"))); // NOI18N
        b11.setText("PRODUCT MANAGEMENT");
        b11.setContentAreaFilled(false);
        b11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b11MouseExited(evt);
            }
        });
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 290, 140));

        b10.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        b10.setForeground(new java.awt.Color(204, 204, 204));
        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ba.png"))); // NOI18N
        b10.setText("BILL ADMINISTRATION");
        b10.setContentAreaFilled(false);
        b10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b10MouseExited(evt);
            }
        });
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, 290, 240));

        jlbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl.setForeground(new java.awt.Color(127, 209, 255));
        jlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl.setToolTipText("");
        jlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 250, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grad1.png"))); // NOI18N
        jLabel5.setFocusable(false);
        jLabel5.setInheritsPopupMenu(false);
        jLabel5.setRequestFocusEnabled(false);
        jLabel5.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 810, 610));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 27)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(233, 232, 232));
        jLabel10.setText("WELCOME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jButton1.setToolTipText("LOG OUT");
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/login_hover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 100, 90));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home1.png"))); // NOI18N
        jButton2.setToolTipText("HOME");
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/home2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main.png"))); // NOI18N
        jButton12.setToolTipText("PREVIOUS PAGE");
        jButton12.setContentAreaFilled(false);
        jButton12.setHideActionText(true);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main_glow.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -20, 390, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, -20, 390, 180));

        background_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        background_lbl.setMaximumSize(new java.awt.Dimension(1366, 725));
        background_lbl.setMinimumSize(new java.awt.Dimension(1366, 725));
        background_lbl.setPreferredSize(new java.awt.Dimension(1366, 725));
        getContentPane().add(background_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 725));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
    dispose();
    new customermanagement(name1).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    jlbl.setText(""+name1);  // For setting use name to welcome label after getting from login page:
    }//GEN-LAST:event_formWindowOpened

    private void b8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseEntered
    b8.setFont(new Font("ALGERIAN",Font.BOLD,18)); 
    b8.setForeground(Color.white);
    // TODO add your handling code here:
    }//GEN-LAST:event_b8MouseEntered

    private void b8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseExited
        b8.setFont(new Font("BERLIN sans FB",Font.BOLD,14)); 
        b8.setForeground(new java.awt.Color(204,204,204));  
// TODO add your handling code here:
    }//GEN-LAST:event_b8MouseExited

    private void b11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b11MouseEntered
    b11.setFont(new Font("ALGERIAN",Font.BOLD,18));      // TODO add your handling code here:
    b11.setForeground(Color.white);                                 
    }//GEN-LAST:event_b11MouseEntered

    private void b11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b11MouseExited
     b11.setFont(new Font("BERLIN sans FB",Font.BOLD,14));  
     b11.setForeground(new java.awt.Color(204,204,204)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_b11MouseExited

    private void b10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseExited
    b10.setForeground(new java.awt.Color(204,204,204)); 
    b10.setFont(new Font("BERLIN sans FB",Font.BOLD,14)); 
           // TODO add your handling code here:
    }//GEN-LAST:event_b10MouseExited

    private void b10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseEntered
     b10.setFont(new Font("ALGERIAN",Font.BOLD,18)); 
     b10.setForeground(Color.white);
     // TODO add your handling code here:
    }//GEN-LAST:event_b10MouseEntered

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
    final String log=jlbl.getText();
    dispose();
    new productmanagement(log).setVisible(true);      
    }//GEN-LAST:event_b11ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
    dispose();
    new billadministration(name1).setVisible(true);     
    }//GEN-LAST:event_b10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    new login2().setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 dispose();
    new index().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        dispose();
        new login2().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed
                    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agent_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agent_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agent_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agent_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                 new Agent_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b8;
    private javax.swing.JLabel background_lbl;
    private javax.swing.JLabel footer_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlbl;
    // End of variables declaration//GEN-END:variables
}
