
import java.awt.GridLayout;
import java.sql.*;
import javax.swing.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sourabh
 */
public class android extends javax.swing.JFrame {
     Connection con;
    PreparedStatement psmnt = null;
    ResultSet rs;
    ImageIcon format;
String name1;
    /**
     * Creates new form android
     */
    public android() {
        initComponents();
    }
    
public android(String log) {
        name1=log;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        p = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cartbut = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        crt = new javax.swing.JLabel();
        jlbl1 = new javax.swing.JLabel();
        jlbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHOPIFY MOBILES - SHOP MOBILES BY CATEGORIES");
        setPreferredSize(new java.awt.Dimension(1378, 730));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -30, 390, 180));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                            shopping  habits  sorted  out  .....");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 490, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, -30, 390, 180));

        n.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        n.setForeground(new java.awt.Color(127, 209, 255));
        n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n.setIcon(new javax.swing.ImageIcon(getClass().getResource("/andhead.png"))); // NOI18N
        n.setToolTipText("");
        n.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 370, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home1.png"))); // NOI18N
        jButton2.setToolTipText("HOME");
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/home2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton12.setToolTipText("PREVIOUS PAGE");
        jButton12.setContentAreaFilled(false);
        jButton12.setHideActionText(true);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/back2.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 300, 130));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout1.png"))); // NOI18N
        jButton3.setToolTipText("LOG OUT");
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/logout2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 100, 140));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        p.setBackground(new java.awt.Color(231, 230, 230));
        p.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 180, 234)), new javax.swing.border.LineBorder(new java.awt.Color(0, 163, 219), 1, true)));
        p.setAutoscrolls(true);
        p.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane2.setViewportView(p);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 920, 420));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sidebanner.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 420));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 1550, 10));

        cartbut.setContentAreaFilled(false);
        cartbut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/cartglow.png"))); // NOI18N
        cartbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbutActionPerformed(evt);
            }
        });
        getContentPane().add(cartbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 130, 60, 50));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(233, 232, 232));
        jLabel10.setText(" HELLO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 140, 70, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1550, 10));

        crt.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        crt.setForeground(new java.awt.Color(127, 209, 255));
        crt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car1t.png"))); // NOI18N
        crt.setToolTipText("");
        crt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(crt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 130, 110, 60));

        jlbl1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlbl1.setForeground(new java.awt.Color(127, 209, 255));
        jlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl1.setText("0");
        jlbl1.setToolTipText("");
        jlbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 130, 40, 30));

        jlbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 15)); // NOI18N
        jlbl.setForeground(new java.awt.Color(127, 209, 255));
        jlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl.setToolTipText("");
        jlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 150, 110, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sidebanner.gif"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 250, 210, 420));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                                                                        Copyright © Shopify Mobiles. All rights reserved.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, 1910, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new index().setVisible(true);
        JOptionPane.showMessageDialog(null,"LOGGED OUT SUCCESSFULLY....");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        dispose();
        new shopbybrands(name1).setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new login1().setVisible(true);
        JOptionPane.showMessageDialog(null,"LOGGED OUT SUCCESSFULLY....");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  int n=0;
        try{       
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt=con.createStatement();
        String sql="SELECT COUNT(*) FROM login1 where username='"+name1+"';";
         ResultSet rs=stmt.executeQuery(sql);
         while(rs.next()){
        n=rs.getInt(1);
        }
        if(n==0){
            name1="GUEST";
        }
        else{
            name1=name1;
        }
    }
    catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
    }
        jlbl.setText(""+name1);    
     int ct=0;
     try{       
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt=con.createStatement();
        String sql="SELECT COUNT(*) FROM cart where username='"+name1+"'";
         ResultSet rs=stmt.executeQuery(sql);
         while(rs.next()){
        ct=rs.getInt(1);
        }
        jlbl1.setText(""+ct);
    }
    catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
    }
int count=0;
try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
            Statement stmt=con.createStatement();
            String sql = null;
                sql="select brand,model,price,colour,dom,camerares,storage,type,ram,os,sim,pid from mobiles where os='android';";
            ResultSet rs=stmt.executeQuery(sql);
            boolean rec=rs.next();
            if(!rec){
                JOptionPane.showMessageDialog(null,"error","SORRY!! NO ITEMS FOUND",JOptionPane.ERROR_MESSAGE);
            }
            do{
                String brand1=rs.getString(1);
                String model1=rs.getString(2);
                String price1=rs.getString(3);
                String colour1=rs.getString(4);
                String dom1=rs.getString(5);
                String camera1=rs.getString(6);
                String storage1=rs.getString(7);
                String type1=rs.getString(8);
                String ram1=rs.getString(9);
                String os1=rs.getString(10);
                String sim1=rs.getString(11);
                int pid=rs.getInt(12);
                
             GridLayout layout =new GridLayout(1,2);
            p.setLayout(layout);
            Class .forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
            String query = "select * from productpic where pid="+pid+";";
            psmnt = con.prepareStatement(query);
            rs=psmnt.executeQuery();
            rs.next();
            byte[] imagedata=rs.getBytes(2);
            format=new ImageIcon(imagedata);
            JLabel img=new JLabel("");
            p.add(img);
            img.setIcon(format);
            JLabel mode=new JLabel("");
            mode.setText("<html><font size=5><b>"+brand1+" "+model1+'\n');
            JLabel pr=new JLabel(""+"<html><font size=5><b>RS "+price1+"</b></html>");

            JLabel f=new JLabel(mode.getText()+pr.getText()+"<html><br><font size=3><b> "+"  "+ram1+" RAM</b></html>");
            p.add(f);
            p.revalidate();
            p.repaint();
            }while(rs.next());
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void cartbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbutActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cartbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(android.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(android.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(android.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(android.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new android().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cartbut;
    private javax.swing.JLabel crt;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlbl;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel n;
    private javax.swing.JPanel p;
    // End of variables declaration//GEN-END:variables
}
