import java.sql.*;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sourabh
 */
public class billadministration extends javax.swing.JFrame {
    String log,value1="",value2="",value3,value4;
    String user;
     int totprice=0;
int i;
Timer t;
    /**
     * Creates new form index2
     */
    public billadministration(){     
        initComponents();
       
    }
        public billadministration(String name1) {
        log=name1;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill_dlg = new javax.swing.JDialog();
        footer_lbl1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jlbl2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        untf = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        billtable = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        qtytf = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        piddd = new javax.swing.JComboBox();
        pb1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        dc3 = new com.toedter.calendar.JDateChooser();
        bill = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rid01 = new javax.swing.JLabel();
        tp3 = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        lbladd3 = new javax.swing.JLabel();
        lbladd2 = new javax.swing.JLabel();
        lbladd5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billtable1 = new javax.swing.JTable();
        lbladd6 = new javax.swing.JLabel();
        tp2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbladd8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbladd9 = new javax.swing.JLabel();
        lbladd10 = new javax.swing.JLabel();
        lbladd11 = new javax.swing.JLabel();
        lbladd12 = new javax.swing.JLabel();
        lbladd13 = new javax.swing.JLabel();
        lbladd14 = new javax.swing.JLabel();
        lbladd15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customer = new javax.swing.JTextArea();
        lbladd16 = new javax.swing.JLabel();
        tp1 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        show = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dc1 = new com.toedter.calendar.JDateChooser();
        rid = new javax.swing.JLabel();
        tp4 = new javax.swing.JLabel();
        bcn = new javax.swing.JLabel();
        nb = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        bnkdet = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jpt7 = new javax.swing.JTextField();
        jpt2 = new javax.swing.JTextField();
        jpt3 = new javax.swing.JTextField();
        jpt4 = new javax.swing.JTextField();
        jpt5 = new javax.swing.JTextField();
        jpt6 = new javax.swing.JTextField();
        jrb2 = new javax.swing.JRadioButton();
        jrb1 = new javax.swing.JRadioButton();
        jpt1 = new javax.swing.JTextField();
        jpt8 = new javax.swing.JPasswordField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jpt9 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        dc2 = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jrb3 = new javax.swing.JRadioButton();
        jrb4 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDialogsch = new javax.swing.JDialog();
        jlbl3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        c1 = new javax.swing.JTable();
        jlbl4 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        footer_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jlbl1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        background_lbl = new javax.swing.JLabel();

        bill_dlg.setTitle("BILL");
        bill_dlg.setMaximumSize(new java.awt.Dimension(1366, 720));
        bill_dlg.setMinimumSize(new java.awt.Dimension(1366, 720));
        bill_dlg.setPreferredSize(new java.awt.Dimension(1366, 720));
        bill_dlg.setResizable(false);
        bill_dlg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                bill_dlgWindowOpened(evt);
            }
        });
        bill_dlg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footer_lbl1.setBackground(new java.awt.Color(0, 0, 0));
        footer_lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        footer_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        footer_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer_lbl1.setText("   Copyright © SASOFTECH TECHNOLOGY SOLUTIONS. All rights reserved.");
        footer_lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        footer_lbl1.setMaximumSize(new java.awt.Dimension(1366, 17));
        footer_lbl1.setMinimumSize(new java.awt.Dimension(1366, 17));
        footer_lbl1.setOpaque(true);
        footer_lbl1.setPreferredSize(new java.awt.Dimension(1366, 17));
        bill_dlg.getContentPane().add(footer_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, -1, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("                                                            shopping  habits  sorted  out  .....");
        bill_dlg.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 490, 50));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head1.png"))); // NOI18N
        bill_dlg.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -20, 390, 180));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head2.png"))); // NOI18N
        bill_dlg.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -20, 390, 180));

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 27)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(233, 232, 232));
        jLabel26.setText("WELCOME");
        bill_dlg.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main.png"))); // NOI18N
        jButton18.setToolTipText("PREVIOUS PAGE");
        jButton18.setContentAreaFilled(false);
        jButton18.setHideActionText(true);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main_glow.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        bill_dlg.getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jButton8.setToolTipText("LOG OUT");
        jButton8.setContentAreaFilled(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_hover.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        bill_dlg.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 100, 80));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home1.png"))); // NOI18N
        jButton9.setToolTipText("HOME");
        jButton9.setContentAreaFilled(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/home2.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        bill_dlg.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        jlbl2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl2.setForeground(new java.awt.Color(127, 209, 255));
        jlbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl2.setToolTipText("");
        jlbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bill_dlg.getContentPane().add(jlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 250, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BILL DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("UserName :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        untf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        untf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                untfActionPerformed(evt);
            }
        });
        untf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                untfFocusGained(evt);
            }
        });
        jPanel1.add(untf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 20));

        billtable.setAutoCreateRowSorter(true);
        billtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "ITEM", "UNIT COST", "QUANTITY ", "LINE TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        billtable.setCellSelectionEnabled(true);
        billtable.setGridColor(new java.awt.Color(153, 0, 153));
        billtable.setOpaque(false);
        billtable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(billtable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 760, 150));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("PRODUCT ID:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, 40));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setForeground(new java.awt.Color(204, 204, 204));
        jButton10.setText("GENERATE BILL");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        qtytf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        qtytf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtytfActionPerformed(evt);
            }
        });
        jPanel1.add(qtytf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, 20));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("QUANTITY");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 40));

        buttonGroup1.add(cash);
        cash.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cash.setForeground(new java.awt.Color(255, 255, 255));
        cash.setText("CASH");
        cash.setContentAreaFilled(false);
        jPanel1.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        buttonGroup1.add(card);
        card.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        card.setForeground(new java.awt.Color(255, 255, 255));
        card.setText("CARD");
        card.setOpaque(false);
        card.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cardItemStateChanged(evt);
            }
        });
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });
        jPanel1.add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setForeground(new java.awt.Color(204, 204, 204));
        jButton11.setText("ADD PRODUCT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 130, 30));

        piddd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidddActionPerformed(evt);
            }
        });
        jPanel1.add(piddd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 240, -1));

        bill_dlg.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 810, 340));

        pb1.setBackground(new java.awt.Color(30, 172, 219));
        pb1.setForeground(new java.awt.Color(0, 0, 0));
        pb1.setBorderPainted(false);
        bill_dlg.getContentPane().add(pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1910, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        bill_dlg.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        dc3.setBackground(new java.awt.Color(204, 204, 204));
        dc3.setForeground(new java.awt.Color(204, 204, 204));
        dc3.setToolTipText("Enter DOB");
        dc3.setOpaque(false);
        bill_dlg.getContentPane().add(dc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        bill.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        bill.setMaximumSize(new java.awt.Dimension(2147483647, 725));
        bill.setMinimumSize(new java.awt.Dimension(600, 725));
        bill.setPreferredSize(new java.awt.Dimension(592, 725));
        bill.setResizable(false);
        bill.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                billWindowOpened(evt);
            }
        });
        bill.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(2190, 850));
        jPanel2.setMinimumSize(new java.awt.Dimension(842, 592));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(2190, 850));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 38)); // NOI18N
        jLabel14.setText("INVOICE");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 3, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BILL.jpg"))); // NOI18N
        jLabel11.setText("shopify mobile");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 540, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                                                            shopping habits sorted out ...");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 20));

        rid01.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(rid01, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 90, 50));

        tp3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tp3.setText("SHOPIFY MOBILES PVT. LTD.");
        jPanel2.add(tp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 180, 20));

        dt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 90, 20));

        lbladd3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd3.setText("AMOUNT");
        jPanel2.add(lbladd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 90, 40));

        lbladd2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd2.setText("TYPE                            :");
        jPanel2.add(lbladd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 150, 20));

        lbladd5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbladd5.setText("* PAYMENT SHOULD BE MADE CASH OR BANK TRANSFERS PAYABLE TO SHOPIFY MOBILES");
        jPanel2.add(lbladd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 570, 20));

        billtable1.setAutoCreateRowSorter(true);
        billtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "ITEM", "UNIT COST", "QUANTITY ", "LINE TOTAL"
            }
        ));
        billtable1.setGridColor(new java.awt.Color(153, 0, 153));
        billtable1.setOpaque(false);
        billtable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(billtable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 570, 150));

        lbladd6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd6.setText("INVOICE#");
        jPanel2.add(lbladd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 90, 50));

        tp2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tp2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(tp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 110, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 560, 10));

        lbladd8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd8.setText("INVOICE DATE");
        jPanel2.add(lbladd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 90, 60));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 180, 10));

        lbladd9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd9.setText("TOTAL");
        jPanel2.add(lbladd9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 40, 20));

        lbladd10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladd10.setText("THANKS FOR SHOPPING!!!");
        jPanel2.add(lbladd10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 590, 20));

        lbladd11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd11.setText("BENEFICIARY`S NAME  :");
        jPanel2.add(lbladd11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 150, 20));

        lbladd12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd12.setText("NAME OF BANK            :");
        jPanel2.add(lbladd12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 150, 20));

        lbladd13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd13.setText("BANK CARD NO           :");
        jPanel2.add(lbladd13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 150, 20));

        lbladd14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbladd14.setText("<HTML><U>PAYMENT DETAILS</U>");
        jPanel2.add(lbladd14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 120, 70));

        lbladd15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd15.setText("REFERENCE ID             :");
        jPanel2.add(lbladd15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, 20));

        customer.setEditable(false);
        customer.setColumns(20);
        customer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customer.setLineWrap(true);
        customer.setRows(5);
        customer.setWrapStyleWord(true);
        customer.setBorder(null);
        customer.setCaretColor(new java.awt.Color(255, 255, 255));
        customer.setFocusable(false);
        customer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jScrollPane2.setViewportView(customer);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 350, 90));

        lbladd16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladd16.setText("SUBTOTAL");
        jPanel2.add(lbladd16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 70, 30));

        tp1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tp1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(tp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 110, 30));

        tp.setEditable(false);
        tp.setBackground(new java.awt.Color(204, 204, 204));
        tp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tp.setBorder(null);
        jPanel2.add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 195, 110, 10));

        show.setEditable(false);
        show.setBackground(new java.awt.Color(204, 204, 204));
        show.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        show.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 210, 20));

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 630, 350));

        dc1.setBackground(new java.awt.Color(204, 204, 204));
        dc1.setForeground(new java.awt.Color(204, 204, 204));
        dc1.setToolTipText("Enter DOB");
        dc1.setOpaque(false);
        jPanel2.add(dc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        rid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 120, 20));

        tp4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(tp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 120, 20));

        bcn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(bcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 230, 20));

        nb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(nb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 230, 20));

        bill.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 592, 690));

        jDialog1.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        bnkdet.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTER BANK ACCOUNT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, 40));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CARD NO.");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Last Name :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 40));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 40));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Phone No :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 40));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Date Of Birth :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, 40));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Pincode :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 40));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Gender :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 40));

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("City :");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 40));

        jLabel31.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("UserName :");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 40));

        jpt7.setBackground(new java.awt.Color(204, 204, 204));
        jpt7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jpt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 190, 20));

        jpt2.setBackground(new java.awt.Color(204, 204, 204));
        jpt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jpt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, 20));

        jpt3.setBackground(new java.awt.Color(204, 204, 204));
        jpt3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jpt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 220, 20));

        jpt4.setBackground(new java.awt.Color(204, 204, 204));
        jpt4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jpt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 20));

        jpt5.setBackground(new java.awt.Color(204, 204, 204));
        jpt5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jpt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 220, 20));

        jpt6.setBackground(new java.awt.Color(204, 204, 204));
        jpt6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jpt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 220, 20));

        jrb2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jrb2.setForeground(new java.awt.Color(255, 255, 255));
        jrb2.setText("Female");
        jrb2.setOpaque(false);
        jPanel3.add(jrb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jrb1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jrb1.setForeground(new java.awt.Color(255, 255, 255));
        jrb1.setText("Male");
        jrb1.setOpaque(false);
        jPanel3.add(jrb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 70, -1));

        jpt1.setBackground(new java.awt.Color(204, 204, 204));
        jpt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jpt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 20));

        jpt8.setBackground(new java.awt.Color(204, 204, 204));
        jpt8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jpt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 190, -1));

        jpt9.setBackground(new java.awt.Color(204, 204, 204));
        jpt9.setColumns(20);
        jpt9.setLineWrap(true);
        jpt9.setRows(5);
        jpt9.setWrapStyleWord(true);
        jpt9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setViewportView(jpt9);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 190, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupbutton.gif"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton5.setIconTextGap(0);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, 160));

        dc2.setBackground(new java.awt.Color(204, 204, 204));
        dc2.setForeground(new java.awt.Color(204, 204, 204));
        dc2.setToolTipText("Enter DOB");
        dc2.setOpaque(false);
        jPanel3.add(dc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 190, -1));

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Address :");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, 40));

        jrb3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jrb3.setForeground(new java.awt.Color(255, 255, 255));
        jrb3.setText("Male");
        jrb3.setOpaque(false);
        jPanel3.add(jrb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 70, -1));

        jrb4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jrb4.setForeground(new java.awt.Color(255, 255, 255));
        jrb4.setText("Female");
        jrb4.setOpaque(false);
        jPanel3.add(jrb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jLabel33.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Date Of Birth");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 40));

        bnkdet.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 800, 420));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        bnkdet.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 690));

        jDialogsch.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogsch.setTitle("SEARCH INVOICE");
        jDialogsch.setMinimumSize(new java.awt.Dimension(1020, 320));
        jDialogsch.setName("jDialog1"); // NOI18N
        jDialogsch.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl3.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        jlbl3.setForeground(new java.awt.Color(127, 209, 255));
        jlbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl3.setText("SEARCH BY");
        jlbl3.setToolTipText("");
        jlbl3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialogsch.getContentPane().add(jlbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 990, 30));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in1.png"))); // NOI18N
        jButton12.setContentAreaFilled(false);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/in2.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDialogsch.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 250, 130));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dt1.png"))); // NOI18N
        jButton13.setContentAreaFilled(false);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/dt2.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jDialogsch.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 250, 130));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UN1.png"))); // NOI18N
        jButton14.setContentAreaFilled(false);
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UN2.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jDialogsch.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 250, 130));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jDialogsch.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 460));

        jDialog3.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog3.setTitle("SEARCH CUSTOMER");
        jDialog3.setMinimumSize(new java.awt.Dimension(1040, 340));
        jDialog3.setName("jDialog1"); // NOI18N
        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " INVOICE NO.", " AMOUNT", "TYPE", "CARD NO.", "BANK NAME", "USERNAME", "INVOICE DATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        c1.setOpaque(false);
        jScrollPane5.setViewportView(c1);

        jDialog3.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 990, 200));

        jlbl4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl4.setForeground(new java.awt.Color(127, 209, 255));
        jlbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl4.setText("INVOICE DETAILS");
        jlbl4.setToolTipText("");
        jlbl4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog3.getContentPane().add(jlbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 990, 30));

        jButton15.setBackground(new java.awt.Color(153, 0, 0));
        jButton15.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("EXIT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jDialog3.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 340));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BILL ADMINISTRATION");
        setMinimumSize(new java.awt.Dimension(1378, 725));
        setPreferredSize(new java.awt.Dimension(1378, 725));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footer_lbl.setBackground(new java.awt.Color(0, 0, 0));
        footer_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        footer_lbl.setForeground(new java.awt.Color(255, 255, 255));
        footer_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer_lbl.setText("   Copyright © SASOFTECH TECHNOLOGY SOLUTIONS. All rights reserved.");
        footer_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        footer_lbl.setMaximumSize(new java.awt.Dimension(1366, 17));
        footer_lbl.setMinimumSize(new java.awt.Dimension(1366, 17));
        footer_lbl.setOpaque(true);
        footer_lbl.setPreferredSize(new java.awt.Dimension(1366, 17));
        getContentPane().add(footer_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                            shopping  habits  sorted  out  .....");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 490, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -20, 390, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -20, 390, 180));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 27)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(233, 232, 232));
        jLabel10.setText("WELCOME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jlbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl.setForeground(new java.awt.Color(127, 209, 255));
        jlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head5.png"))); // NOI18N
        jlbl.setToolTipText("");
        jlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 580, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jButton1.setToolTipText("LOG OUT");
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/login_hover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 100, 90));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SB1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/SB2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, -1, 300));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GB1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GB2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 300, 300));

        jlbl1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl1.setForeground(new java.awt.Color(127, 209, 255));
        jlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl1.setToolTipText("");
        jlbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 250, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home1.png"))); // NOI18N
        jButton6.setToolTipText("HOME");
        jButton6.setContentAreaFilled(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/home2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DB1.png"))); // NOI18N
        jButton16.setContentAreaFilled(false);
        jButton16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/DB2.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 280, 300));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main.png"))); // NOI18N
        jButton17.setToolTipText("PREVIOUS PAGE");
        jButton17.setContentAreaFilled(false);
        jButton17.setHideActionText(true);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main_glow.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, 70));

        background_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        background_lbl.setMaximumSize(new java.awt.Dimension(1366, 725));
        background_lbl.setMinimumSize(new java.awt.Dimension(1366, 725));
        background_lbl.setPreferredSize(new java.awt.Dimension(1366, 725));
        getContentPane().add(background_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 725));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new login2().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  bill_dlg.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        new index().setVisible(true);      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
        new index2().setVisible(true);
        JOptionPane.showMessageDialog(null,"Logged out successfully.");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jlbl1.setText(""+log);
    }//GEN-LAST:event_formWindowOpened

    private void bill_dlgWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_bill_dlgWindowOpened
jlbl2.setText(""+log);      
try{         
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        String sql1="SELECT * from mobiles";
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery(sql1);
        while(rs.next()){
            piddd.addItem(rs.getInt(5));
        }
  }
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
try{         
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        String sql1="SELECT * from accessories";
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery(sql1);
        while(rs.next()){
            piddd.addItem(rs.getInt(4));
        }
  }
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
pb1.setVisible(false);
    }//GEN-LAST:event_bill_dlgWindowOpened

    private void untfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_untfActionPerformed

    }//GEN-LAST:event_untfActionPerformed

    private void billWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_billWindowOpened
dc1.setVisible(false);
SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
dc1.setCalendar(Calendar.getInstance());
String date=(String)sdf.format(dc1.getDate());   
dt.setText(""+date);  
//FOR INVOICE NO.
  try{         
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        String sql1="SELECT COUNT(*) FROM invoice;";
        Statement st=con.createStatement();
        ResultSet rs1=st.executeQuery(sql1);   
        String sql2="SELECT max(invoiceno) FROM invoice;";
        Statement st2=con.createStatement();
        ResultSet rs2=st2.executeQuery(sql2);
        int count1=0,invno=0;
        while(rs1.next()){
        count1=rs1.getInt(1);
        }  
        if(count1==0){       
                  invno=10000001;   
                }
        else{    
             while(rs2.next()){
              invno=rs2.getInt(1)+1;   
            }     
}
        rid.setText(""+invno);
            rid01.setText(""+invno);
       
       if(cash.isSelected()==true){
       Statement stmt1 = con.createStatement();
       String sqlv="insert into invoice (invoiceno,amount,type,username,invdate) values('"+invno+"','"+totprice+"','CASH','"+user+"','"+date+"');";
       stmt1.executeUpdate(sqlv);
       }
       else{
       Statement stmt12 = con.createStatement();
       String sqlv2="insert into invoice values('"+invno+"','"+totprice+"','CARD','"+value2+"','"+value1+"','"+user+"','"+date+"');";
       stmt12.executeUpdate(sqlv2);
       
  }
  }
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }      
    
    }//GEN-LAST:event_billWindowOpened

    private void qtytfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtytfActionPerformed
 
    }//GEN-LAST:event_qtytfActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
if(billtable.getRowCount()==0){
   JOptionPane.showMessageDialog(null,  "PLEASE ADD ATLEAST ONE PRODUCT","Error",JOptionPane.ERROR_MESSAGE);
}
else{
 String type1="";
 user=untf.getText();
 customer.setText("");
 String customer1="";
        if(user.equals("")) {
            JOptionPane.showMessageDialog(null,  "INVALID USERNAME","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(card.isSelected()==false&&cash.isSelected()==false){
            JOptionPane.showMessageDialog(null,  "SELECT PAYMENT TYPE","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        String sql="select * from customers where UserName='"+user+"' ;";
        ResultSet rs = stmt.executeQuery(sql);
       while(rs.next()){
       String fn=rs.getString(1);
       String ln=rs.getString(2);
       String ad=rs.getString(12);
       String ct=rs.getString(9);
       String st=rs.getString(8);
       String pc=rs.getString(6);
       customer.append(fn+" "+ln+'\n'+ad+'\n'+ct+" "+st+" "+pc+'\n'+"INDIA");
       if(cash.isSelected()){
           tp4.setText("CASH");
           lbladd12.setVisible(false);
           nb.setVisible(false);
           bcn.setVisible(false);
           lbladd13.setVisible(false);
           type1="CASH";
       }
       else{
          tp4.setText("CARD"); 
           lbladd12.setVisible(true);
           nb.setVisible(true);
           bcn.setVisible(true);
           lbladd13.setVisible(true);

          type1="CARD";         
       }
       TableModel m=billtable.getModel();
       billtable1.setModel(m);
       tp.setText("  INR "+totprice);
       tp1.setText("    "+totprice);
       nb.setText(""+value1);
       bcn.setText(""+value2);
       tp2.setText("INR "+totprice);
        i=0;
        pb1.setVisible(true);
        t=new Timer(1/2,new ActionListener(){
            public void actionPerformed(ActionEvent e){
                pb1.setValue(i);
                i++;
                if(i>100){
                    t.stop();
                    bill.setVisible(true);
                    dispose();
                }
            }
        });

        t.start();
        }
        }
    catch(Exception e){
     JOptionPane.showMessageDialog(null, e.getMessage());   
    }}} 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void untfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_untfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_untfFocusGained

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed

    private void cardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cardItemStateChanged

    }//GEN-LAST:event_cardItemStateChanged

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
JTextField field1 = new JTextField();
JTextField field2 = new JTextField();
JTextField field3 = new JTextField();
JTextField field4 = new JTextField();
Object[] message = {
    "BANK NAME:", field1,
    "CARD NO.:", field2,
    "DOB(YYYY/MM/DD):", field3,
    "PASSWORD:", field4,
};
int option = JOptionPane.showConfirmDialog(null, message, "ENTER BANK DETAILS", JOptionPane.OK_CANCEL_OPTION);
if (option == JOptionPane.OK_OPTION)
{   value1 = field1.getText();
    value2 = field2.getText();
    value3 = field3.getText();
    value4 = field4.getText();
}
else{
    cash.setSelected(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_cardActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     
                    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
if(qtytf.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,  "ENETER QUANTITY","Error",JOptionPane.ERROR_MESSAGE);
    }
else{
    
    if(piddd.getSelectedItem().toString().isEmpty()) {
        JOptionPane.showMessageDialog(null,  "INVALID PRODUCTID","Error",JOptionPane.ERROR_MESSAGE);
    }
    else{
        int pid=(int)piddd.getSelectedItem();
        DefaultTableModel model=(DefaultTableModel)billtable.getModel();
        try{
        int qty=Integer.parseInt(qtytf.getText());
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        String sql="select count(*) from mobiles where pid='"+pid+"';";
        int c1=0,c2=0;
        ResultSet rs = stmt.executeQuery(sql);
        while(rs.first()){
            c1=rs.getInt(1);
            break;
        }
        Statement stmtt = con.createStatement();
        String sqlt="select count(*) from accessories where pid='"+pid+"';";
        ResultSet rst = stmtt.executeQuery(sqlt);
        while(rst.first()){
            c2=rst.getInt(1);
            break;
        }
       Statement stmt0 = con.createStatement();
       String sql0="select * from mobiles where pid='"+pid+"' ;";
       ResultSet rs0 = stmt0.executeQuery(sql0);
       Statement stmt1 = con.createStatement();
       String sql1="select * from accessories where pid='"+pid+"' ;";
       ResultSet rss = stmt1.executeQuery(sql1);
       Boolean rec1 = rs0.next();
       Boolean rec2 = rss.next();
        
       if (c1==0&&c2==0) {
            JOptionPane.showMessageDialog(null, "NO PRODUCT DETAIL EXISTS IN DATABASE");
            }
        
       else{
       if(c1!=0){
           while(rs0.first()){
               int price1=rs0.getInt(3);
               String brand=rs0.getString(1);
               String mode=rs0.getString(2).toUpperCase();
               int ltot=price1*qty;
               totprice = totprice+ltot;
               String item=brand+" "+mode;
               model.addRow(new Object[]{pid,item,price1,qty,ltot});
               break;
           }
       }
       else if(c2!=0){
           while(rss.first()){
               int price1=rss.getInt(3);
               String brand=rss.getString(1);
               String acc=rss.getString(5).toUpperCase();
               String mode=rss.getString(6).toUpperCase();
               int ltot=price1*qty;
               totprice = totprice+ltot;
               String item=brand+" "+acc+" "+mode;
               model.addRow(new Object[]{pid,item,price1,qty,ltot});
               break;
       }
       }   
       else{
            JOptionPane.showMessageDialog(null,  "THE PRODUCT DOESNOT EXIST IN DATABASE","Error",JOptionPane.ERROR_MESSAGE);
       }
       }
        }
    catch(Exception e){
     JOptionPane.showMessageDialog(null, e.getMessage());   
    }    
    }
}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jDialogsch.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String invn= JOptionPane.showInputDialog(null, "Enter InvoiceNo");
        if(invn.equals("")) {
            JOptionPane.showMessageDialog(null,  "INVALID INVOICENO.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            DefaultTableModel model=(DefaultTableModel)c1.getModel();
            try{

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
                Statement stmt = con.createStatement();
                model.setRowCount(0);
                String sql="select * from invoice where invoiceno='"+invn+"' ;";
                ResultSet rs = stmt.executeQuery(sql);
                model.setRowCount(0);
                Boolean rec = rs.next();
                if (!rec) {
                    JOptionPane.showMessageDialog(null,  "INVOICE NO. DOESNOT EXIST IN DATABASE ","Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    jDialog3.setVisible(true);
                    do{
                        String in=rs.getString(1);
                        String am=rs.getString(2);
                        String tp=rs.getString(3);
                        String cn=rs.getString(4);
                        String bn=rs.getString(5);
                        String un=rs.getString(6);
                        String id=rs.getString(7);
                        model.addRow(new Object[]{in,am,tp,cn,bn,un,id});
                    }while(rs.next());
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String invdt= JOptionPane.showInputDialog(null, "Enter Invoice Date(YYYY/MM/DD)");
        if(invdt.equals("")) {
            JOptionPane.showMessageDialog(null,  "INVALID DATE","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            DefaultTableModel model=(DefaultTableModel)c1.getModel();
            try{

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
                Statement stmt = con.createStatement();
                model.setRowCount(0);
               String sql="select * from invoice where invDATE='"+invdt+"' ;";
                ResultSet rs = stmt.executeQuery(sql);
                model.setRowCount(0);
                Boolean rec = rs.next();
                if (!rec) {
                    JOptionPane.showMessageDialog(null,  "NO INVOICE ON SPECIFIED DATE ","Error",JOptionPane.ERROR_MESSAGE);
               }
                else{
                    jDialog3.setVisible(true);
                    do{
                        String in=rs.getString(1);
                        String am=rs.getString(2);
                        String tp=rs.getString(3);
                        String cn=rs.getString(4);
                        String bn=rs.getString(5);
                        String un=rs.getString(6);
                        String id=rs.getString(7);
                        model.addRow(new Object[]{in,am,tp,cn,bn,un,id});
                    }while(rs.next());
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String user= JOptionPane.showInputDialog(null, "Enter User Name");
        if(user.equals("")) {
            JOptionPane.showMessageDialog(null,  "INVALID USERNAME","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            DefaultTableModel model=(DefaultTableModel)c1.getModel();
            try{

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
                Statement stmt = con.createStatement();
                String sql="select * from invoice where UserName='"+user+"' ;";
                ResultSet rs = stmt.executeQuery(sql);
                model.setRowCount(0);
                Boolean rec = rs.next();
                if (!rec) {
                    JOptionPane.showMessageDialog(null,  "USERNAME DOESNOT EXIST IN INVOICE DATABASE ","Error",JOptionPane.ERROR_MESSAGE);
               }
                else{
                    jDialog3.setVisible(true);
                    do{
                        String in=rs.getString(1);
                        String am=rs.getString(2);
                        String tp=rs.getString(3);
                        String cn=rs.getString(4);
                        String bn=rs.getString(5);
                        String un=rs.getString(6);
                        String id=rs.getString(7);
                        model.addRow(new Object[]{in,am,tp,cn,bn,un,id});
                    }while(rs.next());
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
            jDialog3.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    int flag;
        String invno= JOptionPane.showInputDialog(null, "Enter InvoiceNo.");
    while (invno.equals("")) {
        JOptionPane.showMessageDialog(null,  "INVALID INVOICENO.","Error",JOptionPane.ERROR_MESSAGE);
        invno= JOptionPane.showInputDialog(null, "Enter InvoiceNo.");
    }
    try {
        flag=0;
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from invoice");
        Boolean rec = rs.next();
        if (!rec) {
            JOptionPane.showMessageDialog(null, "NO INVOICE DETAIL EXISTS IN DATABASE");
            } 
        else{
            do{
                String invno1 = rs.getString(1);
                if (invno.equals(invno1)) {
                    int reply = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE DETAILS OF INVOICE : "+invno +"  FROM THE DATABASE");
                    if (reply == JOptionPane.YES_OPTION) {
                        String sql1="delete from invoice where invoiceno= '"+invno+"' ;";
                        JOptionPane.showMessageDialog(null, "INVOICE IS DELETED SUCCESSFULLY");
                        }
                    else if (reply == JOptionPane.NO_OPTION) {
                        JOptionPane.showMessageDialog(null, "INVOICE IS NOT DELETED");
                        } 
                    else if (reply == JOptionPane.CANCEL_OPTION) {
                        JOptionPane.showMessageDialog(null, "INVOICE IS NOT DELETED");
                        }
                        flag=1;
                }
                }while (rs.next());
                if (flag==0) {
                    JOptionPane.showMessageDialog(null,"THE INVOOICENO. DOESNOT EXIST IN DATABASE","Error",JOptionPane.ERROR_MESSAGE);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        dispose();
        new Agent_page(log).setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        dispose();
        new billadministration(log).setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void pidddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidddActionPerformed
public int print(Graphics g, PageFormat pf, int pi) throws PrinterException
{
    Graphics2D g2 = (Graphics2D) g;
    g2.translate(pf.getImageableX()+5, pf.getImageableY()+5);
    Font  f = new Font("Monospaced",Font.PLAIN,12);
    g2.setFont (f);
    paint (g2);
    return Printable.PAGE_EXISTS;
}
    /**
    * @param args the command line arguments
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billadministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billadministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billadministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billadministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billadministration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_lbl;
    private javax.swing.JLabel bcn;
    private javax.swing.JDialog bill;
    private javax.swing.JDialog bill_dlg;
    private javax.swing.JTable billtable;
    private javax.swing.JTable billtable1;
    private javax.swing.JDialog bnkdet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable c1;
    private javax.swing.JRadioButton card;
    private javax.swing.JRadioButton cash;
    private javax.swing.JTextArea customer;
    private com.toedter.calendar.JDateChooser dc1;
    private com.toedter.calendar.JDateChooser dc2;
    private com.toedter.calendar.JDateChooser dc3;
    private javax.swing.JLabel dt;
    private javax.swing.JLabel footer_lbl;
    private javax.swing.JLabel footer_lbl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialogsch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlbl;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlbl2;
    private javax.swing.JLabel jlbl3;
    private javax.swing.JLabel jlbl4;
    private javax.swing.JTextField jpt1;
    private javax.swing.JTextField jpt2;
    private javax.swing.JTextField jpt3;
    private javax.swing.JTextField jpt4;
    private javax.swing.JTextField jpt5;
    private javax.swing.JTextField jpt6;
    private javax.swing.JTextField jpt7;
    private javax.swing.JPasswordField jpt8;
    private javax.swing.JTextArea jpt9;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    private javax.swing.JLabel lbladd10;
    private javax.swing.JLabel lbladd11;
    private javax.swing.JLabel lbladd12;
    private javax.swing.JLabel lbladd13;
    private javax.swing.JLabel lbladd14;
    private javax.swing.JLabel lbladd15;
    private javax.swing.JLabel lbladd16;
    private javax.swing.JLabel lbladd2;
    private javax.swing.JLabel lbladd3;
    private javax.swing.JLabel lbladd5;
    private javax.swing.JLabel lbladd6;
    private javax.swing.JLabel lbladd8;
    private javax.swing.JLabel lbladd9;
    private javax.swing.JLabel nb;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JComboBox piddd;
    private javax.swing.JTextField qtytf;
    private javax.swing.JLabel rid;
    private javax.swing.JLabel rid01;
    private javax.swing.JTextField show;
    private javax.swing.JTextField tp;
    private javax.swing.JLabel tp1;
    private javax.swing.JLabel tp2;
    private javax.swing.JLabel tp3;
    private javax.swing.JLabel tp4;
    private javax.swing.JTextField untf;
    // End of variables declaration//GEN-END:variables
}
