import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sourabh
 */
public class customer_profile extends javax.swing.JFrame {
    public Date d=null;Time tme=null;
    
            Border border=BorderFactory.createLineBorder(Color.red, 2, rootPaneCheckingEnabled);
            Border border1=BorderFactory.createLineBorder(Color.green, 1, rootPaneCheckingEnabled);
    String name1;
        int i;
        int count;
        Timer t;
    /**
     * Creates new form signup
     */
    public customer_profile() {
        initComponents();
        
    }
    public customer_profile(String log) {
        name1=log;
        initComponents();
     if(name1=="null"){
         name1="GUEST";
     }
     else{
     name1=log.toUpperCase();
     } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        password_dialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        password_pwdfld = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        change_password_dlg = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        renew_password_pfld = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        new_password_pfld = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        password_1_pwdfld = new javax.swing.JPasswordField();
        change_pass_btn = new javax.swing.JButton();
        invoice_dlg = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        details_1_tbl = new javax.swing.JTable();
        account_creation_date_lbl3 = new javax.swing.JLabel();
        pb1 = new javax.swing.JProgressBar();
        cart_btn = new javax.swing.JButton();
        cart_lbl = new javax.swing.JLabel();
        cart_count_lbl = new javax.swing.JLabel();
        hello_image_btn = new javax.swing.JButton();
        username_btn = new javax.swing.JButton();
        hello_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        advanced_settings_pnl = new javax.swing.JPanel();
        cnt_lbl = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        account_creation_date_lbl1 = new javax.swing.JLabel();
        account_creation_date_lbl = new javax.swing.JLabel();
        account_creation_date_lbl2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        back_2_btn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        details_tbl = new javax.swing.JTable();
        contents_pnl = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        advanced_settings_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        edit_profile_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jpt2 = new javax.swing.JTextField();
        jpt6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jpt31 = new javax.swing.JLabel();
        dc1 = new com.toedter.calendar.JDateChooser();
        jpt7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jrb2 = new javax.swing.JRadioButton();
        jrb1 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpt9 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jcb1 = new javax.swing.JComboBox();
        jpt4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jpt41 = new javax.swing.JLabel();
        jpt3 = new javax.swing.JTextField();
        save_profile_btn = new javax.swing.JButton();
        jpt1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        details_pnl = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        customer_btn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cart_1_lbl = new javax.swing.JLabel();
        customer_since_lbl = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        password_dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        password_dialog.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        password_dialog.setLocationByPlatform(true);
        password_dialog.setMinimumSize(new java.awt.Dimension(400, 201));
        password_dialog.setResizable(false);
        password_dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                password_dialogWindowOpened(evt);
            }
        });
        password_dialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CHANGE ACCOUNT PASSWORD");
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 20));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("For Security Reasons Please Enter Your Password :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        password_pwdfld.setBackground(new java.awt.Color(204, 204, 204));
        password_pwdfld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        password_pwdfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_pwdfldActionPerformed(evt);
            }
        });
        jPanel2.add(password_pwdfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animated-gifs-exclamation-points-008.gif"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 40));

        password_dialog.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        change_password_dlg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        change_password_dlg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        change_password_dlg.setLocationByPlatform(true);
        change_password_dlg.setMinimumSize(new java.awt.Dimension(400, 352));
        change_password_dlg.setResizable(false);
        change_password_dlg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                change_password_dlgWindowOpened(evt);
            }
        });
        change_password_dlg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, -1));

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Re-enter New Password :");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        renew_password_pfld.setBackground(new java.awt.Color(204, 204, 204));
        renew_password_pfld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        renew_password_pfld.setEnabled(false);
        renew_password_pfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renew_password_pfldActionPerformed(evt);
            }
        });
        jPanel7.add(renew_password_pfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 380, -1));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Enter New Password :");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        new_password_pfld.setBackground(new java.awt.Color(204, 204, 204));
        new_password_pfld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        new_password_pfld.setEnabled(false);
        new_password_pfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_password_pfldActionPerformed(evt);
            }
        });
        jPanel7.add(new_password_pfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Hey!! You opted to change your account password");
        jLabel21.setOpaque(true);
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 20));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Please Enter Your Old Password And Press Enter :");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        password_1_pwdfld.setBackground(new java.awt.Color(204, 204, 204));
        password_1_pwdfld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        password_1_pwdfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_1_pwdfldActionPerformed(evt);
            }
        });
        jPanel7.add(password_1_pwdfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 380, -1));

        change_pass_btn.setBackground(new java.awt.Color(232, 165, 84));
        change_pass_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        change_pass_btn.setText("CHANGE PASSWORD");
        change_pass_btn.setEnabled(false);
        change_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_pass_btnActionPerformed(evt);
            }
        });
        jPanel7.add(change_pass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 380, 40));

        change_password_dlg.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        invoice_dlg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        invoice_dlg.setMinimumSize(new java.awt.Dimension(755, 360));
        invoice_dlg.setResizable(false);
        invoice_dlg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                invoice_dlgWindowOpened(evt);
            }
        });
        invoice_dlg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        details_1_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "INVOIVE NO.", "TOTAL AMOUNT", "PAYMENT TYPE", "CARD/ACCOUNT NO.", "BANK NAME", "USERNAME", "INVOICE DATE"
            }
        ));
        details_1_tbl.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(details_1_tbl);

        invoice_dlg.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 740, 280));

        account_creation_date_lbl3.setBackground(new java.awt.Color(0, 0, 51));
        account_creation_date_lbl3.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        account_creation_date_lbl3.setForeground(new java.awt.Color(204, 204, 204));
        account_creation_date_lbl3.setText("Previous invoice details");
        account_creation_date_lbl3.setOpaque(true);
        invoice_dlg.getContentPane().add(account_creation_date_lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1070, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROFILE");
        setMinimumSize(new java.awt.Dimension(1366, 725));
        setResizable(false);
        setState(1);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pb1.setBackground(new java.awt.Color(30, 172, 219));
        pb1.setForeground(new java.awt.Color(0, 0, 0));
        pb1.setBorderPainted(false);
        getContentPane().add(pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 1100, 10));

        cart_btn.setToolTipText("<HTML><BODY BGCOLOR=\"ffe0a8\"><b>CLICK HERE <BR> GO TO YOUR CART</b><body></html>");
        cart_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        cart_btn.setBorderPainted(false);
        cart_btn.setContentAreaFilled(false);
        cart_btn.setMultiClickThreshhold(3000L);
        cart_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/cartglow.png"))); // NOI18N
        cart_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cart_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cart_btnMouseExited(evt);
            }
        });
        cart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cart_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cart_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 90, 102, 50));

        cart_lbl.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        cart_lbl.setForeground(new java.awt.Color(127, 209, 255));
        cart_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cart_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car1t.png"))); // NOI18N
        cart_lbl.setToolTipText("");
        cart_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(cart_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 90, 110, 60));

        cart_count_lbl.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        cart_count_lbl.setForeground(new java.awt.Color(127, 209, 255));
        cart_count_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cart_count_lbl.setText("0");
        cart_count_lbl.setToolTipText("");
        cart_count_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(cart_count_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 90, 40, 30));

        hello_image_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointee_logo.png"))); // NOI18N
        hello_image_btn.setToolTipText("<HTML><BODY BGCOLOR=\"ffe0a8\"><b>CLICK HERE VIEW OR MODIFY YOUR ACCOUNT DETAILS</b><body></html>");
        hello_image_btn.setContentAreaFilled(false);
        hello_image_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hello_image_btnActionPerformed(evt);
            }
        });
        getContentPane().add(hello_image_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, 70, 80));

        username_btn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 15)); // NOI18N
        username_btn.setForeground(new java.awt.Color(187, 229, 252));
        username_btn.setToolTipText("<HTML><BODY BGCOLOR=\"ffe0a8\"><b>CLICK HERE TO VIEW OR MODIFY YOUR ACCOUNT DETAILS</b><body></html>");
        username_btn.setContentAreaFilled(false);
        username_btn.setPreferredSize(new java.awt.Dimension(0, 0));
        username_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_btnActionPerformed(evt);
            }
        });
        getContentPane().add(username_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, 110, 30));

        hello_lbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        hello_lbl.setForeground(new java.awt.Color(233, 232, 232));
        hello_lbl.setText(" HELLO");
        getContentPane().add(hello_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 70, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                            shopping  habits  sorted  out  .....");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 490, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Copyright © SASOFTECH TECHNOLOGY SOLUTIONS. All rights reserved.");
        jLabel6.setMaximumSize(new java.awt.Dimension(1366, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(1366, 17));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(1366, 17));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1366, 30));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        advanced_settings_pnl.setBackground(new java.awt.Color(53, 50, 58));
        advanced_settings_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cnt_lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cnt_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cnt_lbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        advanced_settings_pnl.add(cnt_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 130, 20));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 15, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        account_creation_date_lbl1.setBackground(new java.awt.Color(51, 51, 51));
        account_creation_date_lbl1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        account_creation_date_lbl1.setForeground(new java.awt.Color(204, 204, 204));
        account_creation_date_lbl1.setText("You are with us since :");
        jPanel6.add(account_creation_date_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 30));

        account_creation_date_lbl.setBackground(new java.awt.Color(51, 51, 51));
        account_creation_date_lbl.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        account_creation_date_lbl.setForeground(new java.awt.Color(204, 51, 0));
        jPanel6.add(account_creation_date_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 190, 30));

        advanced_settings_pnl.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 450, 30));

        account_creation_date_lbl2.setBackground(new java.awt.Color(0, 0, 51));
        account_creation_date_lbl2.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        account_creation_date_lbl2.setForeground(new java.awt.Color(204, 204, 204));
        account_creation_date_lbl2.setText("My last login details and previous invoice details");
        account_creation_date_lbl2.setOpaque(true);
        advanced_settings_pnl.add(account_creation_date_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1060, 26));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(237, 236, 236));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_3.png"))); // NOI18N
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/button_3_hover.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        advanced_settings_pnl.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 150, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(237, 236, 236));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_2.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/button_2_hover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        advanced_settings_pnl.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 190, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(237, 236, 236));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_1.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/button_1_hover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        advanced_settings_pnl.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 100, 30));

        back_2_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        back_2_btn.setToolTipText("GO BACK TO BASIC SETTINGS");
        back_2_btn.setContentAreaFilled(false);
        back_2_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_glow.png"))); // NOI18N
        back_2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_2_btnActionPerformed(evt);
            }
        });
        advanced_settings_pnl.add(back_2_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 40, 50));

        details_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USERNAME", "LOGIN DATE", "LOGIN TIME"
            }
        ));
        jScrollPane4.setViewportView(details_tbl);

        advanced_settings_pnl.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, 1060, 390));

        jPanel1.add(advanced_settings_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 1080, 480));

        contents_pnl.setBackground(new java.awt.Color(53, 50, 58));
        contents_pnl.setOpaque(false);
        contents_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("State :");
        contents_pnl.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 40));

        advanced_settings_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/advanced_settings.png"))); // NOI18N
        advanced_settings_btn.setContentAreaFilled(false);
        advanced_settings_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/advanced_settings_glow.png"))); // NOI18N
        advanced_settings_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanced_settings_btnActionPerformed(evt);
            }
        });
        contents_pnl.add(advanced_settings_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 270, 80));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phone No :");
        contents_pnl.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 40));

        edit_profile_btn.setBackground(new java.awt.Color(0, 2, 5));
        edit_profile_btn.setForeground(new java.awt.Color(204, 204, 204));
        edit_profile_btn.setText("EDIT PROFILE DETAILS");
        edit_profile_btn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        edit_profile_btn.setIconTextGap(0);
        edit_profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile_btnActionPerformed(evt);
            }
        });
        contents_pnl.add(edit_profile_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 310, 30));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email :");
        contents_pnl.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 40));

        jpt2.setBackground(new java.awt.Color(204, 204, 204));
        jpt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt2.setDisabledTextColor(new java.awt.Color(78, 78, 78));
        contents_pnl.add(jpt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 220, 20));

        jpt6.setBackground(new java.awt.Color(204, 204, 204));
        jpt6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt6.setDisabledTextColor(new java.awt.Color(78, 78, 78));
        jpt6.setDoubleBuffered(true);
        jpt6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpt6KeyTyped(evt);
            }
        });
        contents_pnl.add(jpt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 220, 20));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pincode :");
        contents_pnl.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 40));

        jpt31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpt31.setForeground(new java.awt.Color(235, 222, 17));
        contents_pnl.add(jpt31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 220, 20));
        contents_pnl.add(dc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 190, -1));

        jpt7.setBackground(new java.awt.Color(204, 204, 204));
        jpt7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt7.setDisabledTextColor(new java.awt.Color(78, 78, 78));
        contents_pnl.add(jpt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 190, 20));

        jPanel3.setBackground(new java.awt.Color(0, 20, 51));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 110));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jrb2);
        jrb2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jrb2.setForeground(new java.awt.Color(255, 255, 255));
        jrb2.setText("Female");
        jrb2.setOpaque(false);
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });
        jPanel3.add(jrb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        buttonGroup1.add(jrb1);
        jrb1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jrb1.setForeground(new java.awt.Color(255, 255, 255));
        jrb1.setText("Male");
        jrb1.setOpaque(false);
        jPanel3.add(jrb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        contents_pnl.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 220, 30));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date Of Birth");
        contents_pnl.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 40));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Last Name :");
        contents_pnl.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 40));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Address :");
        contents_pnl.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, 40));

        jpt9.setBackground(new java.awt.Color(204, 204, 204));
        jpt9.setColumns(20);
        jpt9.setLineWrap(true);
        jpt9.setRows(5);
        jpt9.setWrapStyleWord(true);
        jpt9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt9.setDisabledTextColor(new java.awt.Color(78, 78, 78));
        jScrollPane1.setViewportView(jpt9);

        contents_pnl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 190, 100));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Gender :");
        contents_pnl.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANDHRA PRADESH", "ARUNACHAL PRADESH", "ASSAM", "BIHAR", "CHANDIGARH", "CHHATTISGARH", "GOA", "GUJARAT", "HARYANA", "HIMACHAL PRADESH", "JAMMU & KASHMIR", "JHARKHAND", "KARNATAKA", "KERALA", "MADHYA PRADESH", "MAHARASHTRA", "MANIPUR", "MEGHALAYA", "MIZORAM", "NAGALAND", "ODISHA", "PUNJAB", "RAJASTHAN", "SIKKIM", "TAMIL NADU", "TELANGANA", "TRIPURA", "UTTAR PRADESH", "UTTARAKHAND", "WEST BENGAL" }));
        contents_pnl.add(jcb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 190, -1));

        jpt4.setBackground(new java.awt.Color(204, 204, 204));
        jpt4.setColumns(10);
        jpt4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt4.setDisabledTextColor(new java.awt.Color(78, 78, 78));
        jpt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpt4KeyTyped(evt);
            }
        });
        contents_pnl.add(jpt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 220, 20));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("City :");
        contents_pnl.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, 40));

        jpt41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpt41.setForeground(new java.awt.Color(235, 222, 17));
        contents_pnl.add(jpt41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 20));

        jpt3.setBackground(new java.awt.Color(204, 204, 204));
        jpt3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt3.setDisabledTextColor(new java.awt.Color(78, 78, 78));
        contents_pnl.add(jpt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 220, 20));

        save_profile_btn.setBackground(new java.awt.Color(0, 12, 30));
        save_profile_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_profile_btn.setText("SAVE  PROFILE DETAILS");
        save_profile_btn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        save_profile_btn.setIconTextGap(0);
        save_profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_profile_btnActionPerformed(evt);
            }
        });
        contents_pnl.add(save_profile_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 310, 30));

        jpt1.setBackground(new java.awt.Color(204, 204, 204));
        jpt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt1.setDisabledTextColor(new java.awt.Color(78, 78, 78));
        contents_pnl.add(jpt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 20));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("First Name :");
        contents_pnl.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jPanel1.add(contents_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 820, 390));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 150, 490));

        jLabel20.setBackground(new java.awt.Color(0, 20, 51));
        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Please Note: Your account once deleted cannot be recovered or re-registered.                                  ");
        jLabel20.setOpaque(true);
        jLabel20.setPreferredSize(new java.awt.Dimension(1366, 28));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1230, 30));

        jLabel5.setBackground(new java.awt.Color(0, 34, 87));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("My Account");
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(1366, 28));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 490));

        details_pnl.setBackground(new java.awt.Color(229, 229, 229));
        details_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default_customer_icon.png"))); // NOI18N
        details_pnl.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 100, 90));

        customer_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        customer_btn.setContentAreaFilled(false);
        customer_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customer_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customer_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customer_btnMouseExited(evt);
            }
        });
        customer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_btnActionPerformed(evt);
            }
        });
        details_pnl.add(customer_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, 54));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("CUSTOMER SINCE");
        details_pnl.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("ON ORDER");
        details_pnl.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        cart_1_lbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        details_pnl.add(cart_1_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 70, 30));

        customer_since_lbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        details_pnl.add(customer_since_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 100, 30));

        jPanel1.add(details_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 1080, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1870, 520));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main.png"))); // NOI18N
        back_btn.setToolTipText("PREVIOUS PAGE");
        back_btn.setContentAreaFilled(false);
        back_btn.setHideActionText(true);
        back_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main_glow.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 130, 70));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton7.setToolTipText("HOME");
        jButton7.setContentAreaFilled(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/home2.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, -30, 390, 180));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -30, 390, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1870, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_profile_btnActionPerformed
        password_dialog.setVisible(true);
        JOptionPane.showMessageDialog(null,"TYPE PASSWORD AND PRESS ENTER","INFO",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_save_profile_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int ct=0;
        String year=null;
        try{       
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmte=con.createStatement();
                String qrye="Select year(Account_Creation_Date) from customers where username='"+name1+"';";
                ResultSet rese=stmte.executeQuery(qrye);
                while(rese.first()){
                    year=rese.getString(1);
                    break;
                }
                customer_since_lbl.setText(year);
        Statement stmt=con.createStatement();
        String fname="";
        String sql9="select firstname from customers where username='"+name1+"';";
        Statement stmt9=con.createStatement();
        ResultSet rs9=stmt9.executeQuery(sql9);
        while(rs9.next()){
            fname=rs9.getString(1);                  
        }
        fname=fname.substring(0,1).toUpperCase()+fname.substring(1).toLowerCase();
        customer_btn.setText("<html><b><h2>"+fname+"'s"+"<br>"+"Shopify</html>");
        String sql="SELECT COUNT(*) FROM cart where username='"+name1+"'";
         ResultSet rs=stmt.executeQuery(sql);
         while(rs.next()){
        ct=rs.getInt(1);
        }
        cart_count_lbl.setText(""+ct);
        cart_1_lbl.setText(ct+" items");
    }
    catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
    }
        pb1.setVisible(false);
        advanced_settings_pnl.setVisible(false);
        jpt1.setEnabled(false);
        jpt2.setEnabled(false);
        jpt3.setEnabled(false);
        jpt4.setEnabled(false);
        jpt6.setEnabled(false);
        jpt7.setEnabled(false);
        jpt9.setEnabled(false);
        dc1.setEnabled(false);
        jrb1.setEnabled(false);
        jrb2.setEnabled(false);
        jcb1.setEnabled(false);  
        save_profile_btn.setVisible(false);
        customer_profile.this.setTitle("YOU ARE LOGGED IN AS "+name1.toUpperCase(Locale.FRENCH));
        username_btn.setText(name1);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();        
            String sql="SELECT * FROM CUSTOMERS WHERE USERNAME='"+name1+"';";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next()){
            d=rs.getDate(13);
            tme=rs.getTime(14);
            jpt1.setText(rs.getString(1));
            jpt2.setText(rs.getString(2));
            jpt3.setText(rs.getString(3));
            jpt4.setText(rs.getString(4));
            jpt6.setText(rs.getString(6));
            jpt7.setText(rs.getString(9));
            dc1.setDate(rs.getDate(11));
            jpt9.setText(rs.getString(12));
            if(rs.getString(7).equals("M")){
                jrb1.setSelected(true);
            }
            else{
                jrb2.setSelected(true);
            }
            jcb1.setSelectedItem(rs.getString(8)); 
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
         //PHONE AND EMAIL VALIDATION STARTS HERE
       Thread t1 = new Thread(new Runnable(){
            private int counter1 = 0;
            public void run() {
                while (true){
                    counter1++;
                    SwingUtilities.invokeLater(new Runnable(){
                        public void run() {
                            if (counter1 % 2 == 0){
                            try{
                                Class.forName("com.mysql.jdbc.Driver");
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
                                Statement stmt=con.createStatement();
                                String qry="select email,phoneno from customers where not username='"+name1+"';";
                                ResultSet res=stmt.executeQuery(qry);
                                String em,un;
                                String pn;      
                                em=jpt3.getText();           
                                pn=jpt4.getText();
                                int flag1 = 0,flag2 = 0,flag3 = 0;
                                Border border=BorderFactory.createLineBorder(Color.red, 2, rootPaneCheckingEnabled);
                                while(res.next()){
                                    if(em.equalsIgnoreCase(res.getString(1))){
                                          jpt31.setText("EMAIL ALREADY EXISTS");
                                          jpt3.setBorder(border);
                                          flag1=1;
                                          save_profile_btn.setEnabled(false);
                                    }
                                    if(pn.equals(res.getString(2))){
                                          jpt41.setText("PHONE NO ALREADY EXISTS");
                                          jpt4.setBorder(border);
                                          flag2=1;
                                          save_profile_btn.setEnabled(false);
                                    }
                                }
                                if(flag1!=1){
                                    save_profile_btn.setEnabled(true);
                                    jpt31.setText(null);
                                    jpt3.setBorder(jpt1.getBorder());
                                }
                                if(flag2!=1){
                                    save_profile_btn.setEnabled(true);
                                    jpt41.setText(null);
                                    jpt4.setBorder(jpt1.getBorder());
                                }
                                res.close();
                                con.close();
                                stmt.close();
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null,e.getMessage());
//                                JOptionPane.showMessageDialog(null,"SORRY!! AN ERROR CREPT");
                            }
                            counter1 = 0;
                            } 
                            else {
                            }
                        }
                    });
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        t1.start();         
        //PHONE AND EMAIL VALIDATION ENDS HERE
    }//GEN-LAST:event_formWindowOpened

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        new mobilebrands(name1,null).setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
        new index().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jpt4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpt4KeyTyped
  if(jpt4.getText().length()>9&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
         }
    }//GEN-LAST:event_jpt4KeyTyped

    private void jpt6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpt6KeyTyped
       if(jpt6.getText().length()>5&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
         }
    }//GEN-LAST:event_jpt6KeyTyped

    private void password_dialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_password_dialogWindowOpened
        password_dialog.setLocationRelativeTo(null);
        password_dialog.setTitle("YOU ARE LOGGED IN AS "+name1.toUpperCase(Locale.FRENCH));
    }//GEN-LAST:event_password_dialogWindowOpened
    private void password_pwdfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_pwdfldActionPerformed
            String pass1=new String(password_pwdfld.getPassword());
            try{                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
                Statement stmt=con.createStatement();
                String qry="Select * from customers where username='"+name1+"';";
                ResultSet res=stmt.executeQuery(qry);
                while(res.first()){
                    if(res.getString("password").equals(pass1)){                        
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con11 = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
            Statement stmt11=con.createStatement();
            String fn,ln,em,un,gen="",city,add,pass,state,dob;
            String pn,pc;
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
            fn=jpt1.getText();
            ln=jpt2.getText();
            em=jpt3.getText();
            pn=jpt4.getText();
            pc=jpt6.getText();
            city=jpt7.getText();
            dc1.setCalendar(Calendar.getInstance());
            dob=(String)sdf.format(dc1.getDate());          
            add=jpt9.getText();
            if(jrb1.isSelected()==true){
                gen="M";
            }
            else if(jrb2.isSelected()==true){
                gen="F";
            }
            state=(String) jcb1.getSelectedItem();            
            if(fn==""||ln==""||em==""||pn==""||pc==""||city==""||add==""||gen==""||state==""||dob.isEmpty()){
                JOptionPane.showMessageDialog(null,"ALL THE FIELDS ARE REQUIRED");
            }
            else{
                int conf=JOptionPane.showConfirmDialog(null,"First Name :" +fn+" Last Name :" +ln+" email :"+em+" Phone No :" +pn+" Pincode :"+pc+" Gender :"+gen+" City :"+city+" Address :"+add+" State :"+state+" DOB :","Confirmation",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);                
                if(conf==JOptionPane.YES_NO_OPTION){
                    String sql11="update customers set firstname='"+fn+"', lastname='"+ln+"', email='"+em+"', phoneno='"+pn+"', pincode='"+pc+"', gender='"+gen+"',state='"+state+"', city='"+city+"', dob='"+dob+"', address='"+add+"' where username='"+name1+"';";
                    stmt11.executeUpdate(sql11);
                    password_pwdfld.setBorder(border1);
                    JOptionPane.showMessageDialog( this,"RECORDS UPDATED SUCCESSFULLY");
                    password_dialog.setVisible(false);
                    new customer_profile(name1).setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Please Check the Details");
                }    
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
                    }
                    else{
                                                try {
                            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("bleep.wav").getAbsoluteFile());
                            Clip clip = AudioSystem.getClip();
                            clip.open(audioInputStream);
                            clip.start();
                        }
       catch(IOException | LineUnavailableException | UnsupportedAudioFileException ex)
       {
         System.out.println("Error with playing sound.");
       }

                        password_pwdfld.setBorder(border);
                        JOptionPane.showMessageDialog(null,"error","INVALID PASSWORD!!!",JOptionPane.WARNING_MESSAGE);
                    }
                    break;
                }
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_password_pwdfldActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
    }//GEN-LAST:event_jrb2ActionPerformed

    private void edit_profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile_btnActionPerformed
        save_profile_btn.setVisible(true);
        edit_profile_btn.setVisible(false);
        jpt1.setEnabled(true);
        jpt2.setEnabled(true);
        jpt3.setEnabled(true);
        jpt4.setEnabled(true);
        jpt6.setEnabled(true);
        jpt7.setEnabled(true);
        jpt9.setEnabled(true);
        dc1.setEnabled(true);
        jrb1.setEnabled(true);
        jrb2.setEnabled(true);
        jcb1.setEnabled(true);  
    }//GEN-LAST:event_edit_profile_btnActionPerformed

    private void username_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_btnActionPerformed
        new customer_profile(name1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_username_btnActionPerformed

    private void hello_image_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hello_image_btnActionPerformed
        username_btn.doClick();
    }//GEN-LAST:event_hello_image_btnActionPerformed

    private void advanced_settings_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanced_settings_btnActionPerformed
        details_pnl.setVisible(false);
        advanced_settings_pnl.setVisible(true);
        contents_pnl.setVisible(false);
        DefaultTableModel model=(DefaultTableModel)details_tbl.getModel();
        int cnt=0;
        try{
        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        String sql="select * from login1 where UserName='"+name1+"' ;";
        ResultSet rs = stmt.executeQuery(sql);
        model.setRowCount(0);
        SimpleDateFormat sdf0= new SimpleDateFormat("dd-MMMMMMMMMM-YYYY");
        Boolean rec = rs.next();
        if (!rec) {
            }
       else{
       do{
       cnt++;
       model.addRow(new Object[]{cnt,rs.getString(1),sdf0.format(rs.getDate(2)),rs.getString(3)});
       details_tbl.setModel(model);
       }while(rs.next());
       cnt_lbl.setText("Total "+cnt+" Logins.");
       }
       model.addRow(new Object[]{"","","",""});
       details_tbl.setModel(model);
     
    }
    catch(Exception e){
//     JOptionPane.showMessageDialog(null, e.getMessage());   
    }     
        SimpleDateFormat sdf1= new SimpleDateFormat("MMMMMMMMMM dd");
        SimpleDateFormat sdf2= new SimpleDateFormat("YYYY");
        account_creation_date_lbl.setText(""+sdf1.format(d)+","+sdf2.format(d)+"  "+tme);
         Thread t = new Thread(new Runnable(){
            private int counter = 0;
            public void run() {
                while (true){
                    counter++;
                    SwingUtilities.invokeLater(new Runnable(){
                        public void run() {
                            if (counter % 2 == 0){
                                Color g2 = new Color(187,229,252);
                                account_creation_date_lbl.setForeground(Color.LIGHT_GRAY);
                                counter = 0;
                            } else {
                                account_creation_date_lbl.setForeground(Color.red);
                            }
                        }
                    });
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        t.start();
    }//GEN-LAST:event_advanced_settings_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        int flag=0;
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from customers where username='"+name1+"';");
        Boolean rec = rs.first();
        if (!rec) {
            JOptionPane.showMessageDialog(null, "NO CUSTOMER DETAIL EXISTS IN DATABASE");
            } 
        else{
            do{
                    int reply = JOptionPane.showConfirmDialog(null,name1+" ARE YOU SURE YOU WANT TO DELETE YOUR ACCOUNT PERMANENTLY");
                    if (reply == JOptionPane.YES_OPTION) {
                        String sql1="delete from customers where username= '"+name1+"' ;";
                        Statement stmt1=con.createStatement();
                        stmt1.executeUpdate(sql1);
                        String sql2="delete from LOGIN1 where username= '"+name1+"' ;";
                        Statement stmt2=con.createStatement();
                        stmt2.executeUpdate(sql2);
                        String sql3="delete from cart where username= '"+name1+"' ;";
                        Statement stmt3=con.createStatement();
                        stmt3.executeUpdate(sql3);
                        JOptionPane.showMessageDialog(null, "CUSTOMER` DETAIL IS DELETED SUCCESSFULLY");
                        back_btn.doClick();
                    }
                    else if (reply == JOptionPane.NO_OPTION) {
                        JOptionPane.showMessageDialog(null, "CUSTOMER` DETAIL IS NOT DELETED");
                        } 
                    else if (reply == JOptionPane.CANCEL_OPTION) {
                        JOptionPane.showMessageDialog(null, "CUSTOMER` DETAIL IS NOT DELETED");
                        }
                        flag=1;
                
                }while (rs.next());
                if (flag==0) {
                    JOptionPane.showMessageDialog(null,"THE USERNAME DOESNOT EXIST IN DATABASE","Error",JOptionPane.ERROR_MESSAGE);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void back_2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_2_btnActionPerformed
        contents_pnl.setVisible(true);
        details_pnl.setVisible(true);
        advanced_settings_pnl.setVisible(false);
    }//GEN-LAST:event_back_2_btnActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        change_password_dlg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void password_1_pwdfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_1_pwdfldActionPerformed
            String pass1=new String(password_1_pwdfld.getPassword());
            try{                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
                Statement stmt4=con4.createStatement();
                String qry4="Select password from customers where username='"+name1+"';";
                ResultSet res4=stmt4.executeQuery(qry4);
                while(res4.next()){
                    if(res4.getString(1).equals(pass1)){  
                        password_1_pwdfld.setBorder(border1);
                        password_1_pwdfld.setEnabled(false);                        
                        new_password_pfld.requestFocus();
                        new_password_pfld.setEnabled(true);
                        renew_password_pfld.setEnabled(true);
                        change_pass_btn.setEnabled(true);
                    }
                    else{
                        password_1_pwdfld.setBorder(border);
                        try {
                            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("bleep.wav").getAbsoluteFile());
                            Clip clip = AudioSystem.getClip();
                            clip.open(audioInputStream);
                            clip.start();
                        }
       catch(IOException | LineUnavailableException | UnsupportedAudioFileException ex)
       {
         System.out.println("Error with playing sound.");
       }
                        JOptionPane.showMessageDialog(null,"INVALID PASSWORD!!","WARNING",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            catch(Exception e){
                 JOptionPane.showMessageDialog(null,e.getMessage(),"WARNING",JOptionPane.ERROR_MESSAGE);
                  
            }
        
    }//GEN-LAST:event_password_1_pwdfldActionPerformed

    private void change_password_dlgWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_change_password_dlgWindowOpened
        change_password_dlg.setLocationRelativeTo(null);
    }//GEN-LAST:event_change_password_dlgWindowOpened

    private void new_password_pfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_password_pfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_password_pfldActionPerformed

    private void renew_password_pfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renew_password_pfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renew_password_pfldActionPerformed

    private void change_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pass_btnActionPerformed

        String pass1=new String(new_password_pfld.getPassword());
        String pass2=new String(renew_password_pfld.getPassword());
        if(pass1.equals(pass2)&&!(pass1.equals(null))){
            try{                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
                Statement stmt=con.createStatement();
                String qry="update customers set password='"+pass1+"' where username='"+name1+"';";
                stmt.executeUpdate(qry);
                JOptionPane.showMessageDialog(null,"PASSWORD CHANGED SUCCESSFULLY");
                change_password_dlg.setVisible(false);
            }
            catch(Exception e){
                 JOptionPane.showMessageDialog(null,e.getMessage(),"WARNING",JOptionPane.ERROR_MESSAGE);                  
            }
        }
        else{
             JOptionPane.showMessageDialog(null,"PASSWORDS DON`T MATCH.","WARNING",JOptionPane.ERROR_MESSAGE);     
        }
    }//GEN-LAST:event_change_pass_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
invoice_dlg.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void invoice_dlgWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_invoice_dlgWindowOpened
       DefaultTableModel model=(DefaultTableModel)details_1_tbl.getModel();
        int cnt=0;
        try{        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        String sql="select * from invoice where UserName='"+name1+"' ;";
        ResultSet rs = stmt.executeQuery(sql);
        model.setRowCount(0);
        SimpleDateFormat sdf0= new SimpleDateFormat("dd-MMMMMMMMMM-YYYY");
        Boolean rec = rs.next();
        if (!rec) {
            }
       else{
       do{
       cnt++;
       model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),sdf0.format(rs.getDate(7))});
       details_1_tbl.setModel(model);
       }while(rs.next());
       cnt_lbl.setText("Total "+cnt+" Logins.");
       }
       model.addRow(new Object[]{"","","",""});
       details_1_tbl.setModel(model);
     
    }
    catch(Exception e){
//     JOptionPane.showMessageDialog(null, e.getMessage());   
    }     
 
    }//GEN-LAST:event_invoice_dlgWindowOpened

    private void customer_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_btnMouseEntered
        customer_btn.setForeground(new Color(12,129,201));
    }//GEN-LAST:event_customer_btnMouseEntered

    private void customer_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_btnMouseExited
         customer_btn.setForeground(Color.black);
    }//GEN-LAST:event_customer_btnMouseExited

    private void customer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_btnActionPerformed
        new mycart(name1).setVisible(true);
    }//GEN-LAST:event_customer_btnActionPerformed

    private void cart_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_btnMouseEntered
        cart_btn.setBorderPainted(true);
    }//GEN-LAST:event_cart_btnMouseEntered

    private void cart_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_btnMouseExited
        cart_btn.setBorderPainted(false);
    }//GEN-LAST:event_cart_btnMouseExited

    private void cart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cart_btnActionPerformed
        if(username_btn.getText().equals(null)||username_btn.getText().equalsIgnoreCase("guest")){
            JOptionPane.showMessageDialog(null,"error","PLEASE LOGIN TO PROCEED",JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(Integer.parseInt(cart_count_lbl.getText())==0&&username_btn.getText().equalsIgnoreCase("guest")==false){
                JOptionPane.showMessageDialog(null,"sorry!! your shopping cart is empty","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            else{
                i=0;
                pb1.setVisible(true);
                t=new Timer(8,new ActionListener(){
                    public void actionPerformed(ActionEvent e){
                        pb1.setValue(i);
                        i++;
                        if(i>100){
                            t.stop();
                            new mycart(name1).setVisible(true);
                            dispose();
                        }
                    }
                });
                t.start();
            }
        }
    }//GEN-LAST:event_cart_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account_creation_date_lbl;
    private javax.swing.JLabel account_creation_date_lbl1;
    private javax.swing.JLabel account_creation_date_lbl2;
    private javax.swing.JLabel account_creation_date_lbl3;
    private javax.swing.JButton advanced_settings_btn;
    private javax.swing.JPanel advanced_settings_pnl;
    private javax.swing.JButton back_2_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cart_1_lbl;
    private javax.swing.JButton cart_btn;
    private javax.swing.JLabel cart_count_lbl;
    private javax.swing.JLabel cart_lbl;
    private javax.swing.JButton change_pass_btn;
    private javax.swing.JDialog change_password_dlg;
    private javax.swing.JLabel cnt_lbl;
    private javax.swing.JPanel contents_pnl;
    private javax.swing.JButton customer_btn;
    private javax.swing.JLabel customer_since_lbl;
    private com.toedter.calendar.JDateChooser dc1;
    private javax.swing.JTable details_1_tbl;
    private javax.swing.JPanel details_pnl;
    private javax.swing.JTable details_tbl;
    private javax.swing.JButton edit_profile_btn;
    private javax.swing.JButton hello_image_btn;
    private javax.swing.JLabel hello_lbl;
    private javax.swing.JDialog invoice_dlg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JTextField jpt1;
    private javax.swing.JTextField jpt2;
    private javax.swing.JTextField jpt3;
    private javax.swing.JLabel jpt31;
    private javax.swing.JTextField jpt4;
    private javax.swing.JLabel jpt41;
    private javax.swing.JTextField jpt6;
    private javax.swing.JTextField jpt7;
    private javax.swing.JTextArea jpt9;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JPasswordField new_password_pfld;
    private javax.swing.JPasswordField password_1_pwdfld;
    private javax.swing.JDialog password_dialog;
    private javax.swing.JPasswordField password_pwdfld;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JPasswordField renew_password_pfld;
    private javax.swing.JButton save_profile_btn;
    private javax.swing.JButton username_btn;
    // End of variables declaration//GEN-END:variables
}
