import java.awt.print.PrinterJob;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sourabh
 */
public class customermanagement extends javax.swing.JFrame {
int flag;
String name1;
    /**
     * Creates new form customermanagement
     */
    public customermanagement() {
        initComponents();
    }
public customermanagement(String log) {
        name1=log;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        c1 = new javax.swing.JTable();
        jlbl1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jlbl2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jpt7 = new javax.swing.JTextField();
        jpt2 = new javax.swing.JTextField();
        jpt3 = new javax.swing.JTextField();
        jpt4 = new javax.swing.JTextField();
        jpt6 = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jcb1 = new javax.swing.JComboBox();
        jpt1 = new javax.swing.JTextField();
        jpt8 = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpt9 = new javax.swing.JTextArea();
        dc1 = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        untf = new javax.swing.JTextField();
        jlbl3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        footer_lbl = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        background_lbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("SEARCH CUSTOMER");
        jDialog1.setMinimumSize(new java.awt.Dimension(1040, 340));
        jDialog1.setName("jDialog1"); // NOI18N
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FIRSTNAME", "LASTNAME", "EMAIL", "PHONE NO.", "USERNAME", "PINCODE", "GENDER", "STATE", "CITY", "PASSWORD", "DOB", "ADDRESS"
            }
        ));
        c1.setOpaque(false);
        jScrollPane1.setViewportView(c1);

        jDialog1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 990, 200));

        jlbl1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl1.setForeground(new java.awt.Color(127, 209, 255));
        jlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl1.setText("CUSTOMER DETAILS");
        jlbl1.setToolTipText("");
        jlbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog1.getContentPane().add(jlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 990, 30));

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jDialog1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 340));

        jDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog2.setTitle("SEARCH CUSTOMER");
        jDialog2.setMinimumSize(new java.awt.Dimension(1020, 320));
        jDialog2.setName("jDialog1"); // NOI18N
        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl2.setForeground(new java.awt.Color(127, 209, 255));
        jlbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl2.setText("SEARCH BY");
        jlbl2.setToolTipText("");
        jlbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog2.getContentPane().add(jlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 990, 30));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC1.png"))); // NOI18N
        jButton10.setContentAreaFilled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/PC2.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 250, 130));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FN1.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/FN2.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 250, 130));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UN1.png"))); // NOI18N
        jButton12.setContentAreaFilled(false);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UN2.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 250, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jDialog2.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 460));

        jDialog3.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog3.setTitle("UPDATE CUSTOMER` DETAILS");
        jDialog3.setMinimumSize(new java.awt.Dimension(900, 460));
        jDialog3.setResizable(false);
        jDialog3.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialog3WindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog3WindowOpened(evt);
            }
        });
        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PLEASE PROVIDE SPECIFIED DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("First Name :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 40));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Last Name :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 40));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 40));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone No :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 40));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date Of Birth");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 40));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Pincode :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 40));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Gender :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 40));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("State :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, 40));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("City :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 40));

        jpt7.setBackground(new java.awt.Color(204, 204, 204));
        jpt7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt7.setEnabled(false);
        jPanel1.add(jpt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 190, 20));

        jpt2.setBackground(new java.awt.Color(204, 204, 204));
        jpt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt2.setEnabled(false);
        jPanel1.add(jpt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 220, 20));

        jpt3.setBackground(new java.awt.Color(204, 204, 204));
        jpt3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt3.setEnabled(false);
        jPanel1.add(jpt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 20));

        jpt4.setBackground(new java.awt.Color(204, 204, 204));
        jpt4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt4.setEnabled(false);
        jPanel1.add(jpt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 220, 20));

        jpt6.setBackground(new java.awt.Color(204, 204, 204));
        jpt6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt6.setEnabled(false);
        jPanel1.add(jpt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 220, 20));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.setEnabled(false);
        female.setOpaque(false);
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 80, 40));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.setEnabled(false);
        male.setOpaque(false);
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 70, 40));

        jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANDHRA PRADESH", "ARUNACHAL PRADESH", "ASSAM", "BIHAR", "CHANDIGARH", "CHHATTISGARH", "GOA", "GUJARAT", "HARYANA", "HIMACHAL PRADESH", "JAMMU & KASHMIR", "JHARKHAND", "KARNATAKA", "KERALA", "MADHYA PRADESH", "MAHARASHTRA", "MANIPUR", "MEGHALAYA", "MIZORAM", "NAGALAND", "ODISHA", "PUNJAB", "RAJASTHAN", "SIKKIM", "TAMIL NADU", "TELANGANA", "TRIPURA", "UTTAR PRADESH", "UTTARAKHAND", "WEST BENGAL" }));
        jcb1.setEnabled(false);
        jPanel1.add(jcb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 190, -1));

        jpt1.setBackground(new java.awt.Color(204, 204, 204));
        jpt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt1.setEnabled(false);
        jPanel1.add(jpt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, 20));

        jpt8.setBackground(new java.awt.Color(204, 204, 204));
        jpt8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt8.setEnabled(false);
        jPanel1.add(jpt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 190, -1));

        jpt9.setBackground(new java.awt.Color(204, 204, 204));
        jpt9.setColumns(20);
        jpt9.setLineWrap(true);
        jpt9.setRows(5);
        jpt9.setWrapStyleWord(true);
        jpt9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpt9.setEnabled(false);
        jScrollPane2.setViewportView(jpt9);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 190, 50));

        dc1.setBackground(new java.awt.Color(204, 204, 204));
        dc1.setForeground(new java.awt.Color(204, 204, 204));
        dc1.setToolTipText("Enter DOB");
        dc1.setEnabled(false);
        dc1.setOpaque(false);
        jPanel1.add(dc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 190, -1));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Address :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upd01.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setEnabled(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton5.setIconTextGap(0);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/upd02.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 170, 90));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("UserName :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        untf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        untf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                untfActionPerformed(evt);
            }
        });
        jPanel1.add(untf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 20));

        jDialog3.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 880, 440));

        jlbl3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl3.setForeground(new java.awt.Color(127, 209, 255));
        jlbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl3.setText("UPDATE CUSTOMER DETAILS");
        jlbl3.setToolTipText("");
        jlbl3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog3.getContentPane().add(jlbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 880, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jDialog3.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 710));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 725));
        setMinimumSize(new java.awt.Dimension(1366, 725));
        setPreferredSize(new java.awt.Dimension(1366, 725));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footer_lbl.setBackground(new java.awt.Color(0, 0, 0));
        footer_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        footer_lbl.setForeground(new java.awt.Color(255, 255, 255));
        footer_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer_lbl.setText("   Copyright © SASOFTECH TECHNOLOGY SOLUTIONS. All rights reserved.");
        footer_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        footer_lbl.setMaximumSize(new java.awt.Dimension(1366, 17));
        footer_lbl.setMinimumSize(new java.awt.Dimension(1366, 17));
        footer_lbl.setOpaque(true);
        footer_lbl.setPreferredSize(new java.awt.Dimension(1366, 17));
        getContentPane().add(footer_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, -1, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main.png"))); // NOI18N
        jButton6.setToolTipText("PREVIOUS PAGE");
        jButton6.setContentAreaFilled(false);
        jButton6.setHideActionText(true);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main_glow.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home1.png"))); // NOI18N
        jButton2.setToolTipText("HOME");
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/home2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -20, 390, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -20, 390, 180));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                            shopping  habits  sorted  out  .....");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 480, 60));

        jlbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jlbl.setForeground(new java.awt.Color(127, 209, 255));
        jlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl.setToolTipText("");
        jlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 250, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jButton1.setToolTipText("LOG OUT");
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_hover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 100, 140));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 27)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(233, 232, 232));
        jLabel10.setText("WELCOME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/update2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, 460));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete1.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/delete2.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, -1, 280));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srch1.png"))); // NOI18N
        jButton8.setContentAreaFilled(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/srch2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 210, 290));

        background_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        getContentPane().add(background_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 750));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grad1.png"))); // NOI18N
        jLabel6.setFocusable(false);
        jLabel6.setInheritsPopupMenu(false);
        jLabel6.setRequestFocusEnabled(false);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 810, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new index().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new login2().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jDialog3.setVisible(true);               // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    String user= JOptionPane.showInputDialog(null, "Enter User Name");
    while (user.equals("")) {
        JOptionPane.showMessageDialog(null,  "INVALID USERNAME","Error",JOptionPane.ERROR_MESSAGE);
        user = JOptionPane.showInputDialog(null, "Enter User Name");
    }
    try {
        flag=0;
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from customers");
        Boolean rec = rs.next();
        if (!rec) {
            JOptionPane.showMessageDialog(null, "NO CUSTOMER DETAIL EXISTS IN DATABASE");
            } 
        else{
            do{
                String user1 = rs.getString(5);
                if (user.equals(user1)) {
                    int reply = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE DETAILS OF CUSTOMER WITH USERNAME : "+user +"  FROM THE DATABASE");
                    if (reply == JOptionPane.YES_OPTION) {
                        String sql1="delete from customers where username= '"+user+"' ;";
                        Statement stmt1=con.createStatement();
                        stmt1.executeUpdate(sql1);
                        String sql2="delete from LOGIN1 where username= '"+user+"' ;";
                        Statement stmt2=con.createStatement();
                        stmt2.executeUpdate(sql2);
                        JOptionPane.showMessageDialog(null, "CUSTOMER` DETAIL IS DELETED SUCCESSFULLY");
                        }
                    else if (reply == JOptionPane.NO_OPTION) {
                        JOptionPane.showMessageDialog(null, "CUSTOMER` DETAIL IS NOT DELETED");
                        } 
                    else if (reply == JOptionPane.CANCEL_OPTION) {
                        JOptionPane.showMessageDialog(null, "CUSTOMER` DETAIL IS NOT DELETED");
                        }
                        flag=1;
                }
                }while (rs.next());
                if (flag==0) {
                    JOptionPane.showMessageDialog(null,"THE USERNAME DOESNOT EXIST IN DATABASE","Error",JOptionPane.ERROR_MESSAGE);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
jDialog2.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      jDialog1.setVisible(false);
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
String user= JOptionPane.showInputDialog(null, "Enter User Name");
    if(user.equals("")) {
        JOptionPane.showMessageDialog(null,  "INVALID USERNAME","Error",JOptionPane.ERROR_MESSAGE);
    }
    else{
        DefaultTableModel model=(DefaultTableModel)c1.getModel();
        try{
        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        String sql="select * from customers where UserName='"+user+"' ;";
        ResultSet rs = stmt.executeQuery(sql);
        model.setRowCount(0);
        Boolean rec = rs.next();
        if (!rec) {
            JOptionPane.showMessageDialog(null, "NO CUSTOMER DETAIL EXISTS IN DATABASE");
            }
       else{
       jDialog1.setVisible(true);
       do{
       String fn=rs.getString(1);
       String ln=rs.getString(2);
       String em=rs.getString(3);
       String ph=rs.getString(4);
       String un=rs.getString(5);
       String pc=rs.getString(6);
       String gn=rs.getString(7);
       String st=rs.getString(8);
       String ct=rs.getString(9);
       String ps=rs.getString(10);
       String db=rs.getString(11);  
       String ad=rs.getString(12);
       model.addRow(new Object[]{fn,ln,em,ph,un,pc,gn,st,ct,ps,db,ad});
       }while(rs.next());
       }
    }
    catch(Exception e){
     JOptionPane.showMessageDialog(null, e.getMessage());   
    }
    }    
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
String p= JOptionPane.showInputDialog(null, "Enter Pincode");
    if(p.equals("")) {
        JOptionPane.showMessageDialog(null,  "INVALID USERNAME","Error",JOptionPane.ERROR_MESSAGE);
    }
    else{
        DefaultTableModel model=(DefaultTableModel)c1.getModel();
        try{
        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        model.setRowCount(0);
        ResultSet rs = stmt.executeQuery("select * from customers where pincode= '"+p+"' ;");
        Boolean rec = rs.next();
        if (!rec) {
            JOptionPane.showMessageDialog(null, "NO CUSTOMER DETAIL EXISTS IN DATABASE");
            }
       else{ 
       jDialog1.setVisible(true);
       do{
       String fn=rs.getString(1);
       String ln=rs.getString(2);
       String em=rs.getString(3);
       String ph=rs.getString(4);
       String un=rs.getString(5);
       String pc=rs.getString(6);
       String gn=rs.getString(7);
       String st=rs.getString(8);
       String ct=rs.getString(9);
       String ps=rs.getString(10);
       String db=rs.getString(11);  
       String ad=rs.getString(12);
       model.addRow(new Object[]{fn,ln,em,ph,un,pc,gn,st,ct,ps,db,ad});
        }while(rs.next());
        }
    }
    catch(Exception e){
     JOptionPane.showMessageDialog(null, e.getMessage());   
    }
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
String f= JOptionPane.showInputDialog(null, "Enter FirstName");
    if(f.equals("")) {
        JOptionPane.showMessageDialog(null,  "INVALID FIRSTNAME","Error",JOptionPane.ERROR_MESSAGE);
    }
    else{
        DefaultTableModel model=(DefaultTableModel)c1.getModel();
        try{
        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        model.setRowCount(0);
        ResultSet rs = stmt.executeQuery("select * from customers where firstname= '"+f+"' ;");
        Boolean rec = rs.next();
        if (!rec) {
            JOptionPane.showMessageDialog(null, "NO CUSTOMER DETAIL EXISTS IN DATABASE");
            }
       else{
       jDialog1.setVisible(true);
       do{
       String fn=rs.getString(1);
       String ln=rs.getString(2);
       String em=rs.getString(3);
       String ph=rs.getString(4);
       String un=rs.getString(5);
       String pc=rs.getString(6);
       String gn=rs.getString(7);
       String st=rs.getString(8);
       String ct=rs.getString(9);
       String ps=rs.getString(10);
       String db=rs.getString(11);  
       String ad=rs.getString(12);
       model.addRow(new Object[]{fn,ln,em,ph,un,pc,gn,st,ct,ps,db,ad});
        }while(rs.next());
        }
    }
    catch(Exception e){
     JOptionPane.showMessageDialog(null, e.getMessage());   
    }
    }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            String fn,ln,em,un,gen="",city,add,pass,state,dob;
            String pn,pc;
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
            fn=jpt1.getText();
            ln=jpt2.getText();
            em=jpt3.getText();
            pn=jpt4.getText();
            un=untf.getText();
            pc=jpt6.getText();
            city=jpt7.getText();
            pass=new String(jpt8.getPassword());
            dob=(String)sdf.format(dc1.getDate());    
            add=jpt9.getText();
            if(male.isSelected()==true){
                gen="M";
            }
            else if(female.isSelected()==true){
                gen="F";
            }
            state=(String) jcb1.getSelectedItem();

            if(fn==""||ln==""||em==""||pn==""||un==""||pc==""||city==""||pass==""||add==""||gen==""||state==""||dob.isEmpty()){
                JOptionPane.showMessageDialog(null,"ALL THE FIELDS ARE REQUIRED");
            }

            else{
                int conf=JOptionPane.showConfirmDialog(null,"First Name :" +fn+" Last Name :" +ln+" email :"+em+" Phone No :" +pn+" UserName :"+un+" Pincode :"+pc+" Gender :"+gen+" City :"+city+" Address :"+add+" Password :"+pass+" State :"+state+" DOB :"+dob,"Confirmation",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);

                if(conf==JOptionPane.YES_NO_OPTION){
                    String sql="update customers set firstname='"+fn+"', lastname='"+ln+"', email='"+em+"', phoneno='"+pn+"', pincode='"+pc+"', gender='"+gen+"',state='"+state+"', city='"+city+"', password='"+pass+"', dob='"+dob+"', address='"+add+"';";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog( this,"UPDATED SUCCESSFULLY");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Please Check the Details");
                }
            }
       jpt1.setText("");
       jpt2.setText("");
       jpt3.setText("");
       jpt4.setText("");
       jpt6.setText("");
       jpt7.setText("");
       jpt8.setText("");
       dc1.setCalendar(null);
       untf.setText("" );
       jpt9.setText("");
       jcb1.setSelectedIndex(-1);
       untf.setEnabled(true);
       jpt1.setEnabled(false);
       jpt2.setEnabled(false);
       jpt3.setEnabled(false);
       jpt4.setEnabled(false);
       jpt6.setEnabled(false);
       jpt7.setEnabled(false);
       jpt8.setEnabled(false);
       dc1.setEnabled(false);       
       jpt9.setEnabled(false);
       jButton5.setEnabled(false);
       jcb1.setEnabled(false);
       male.setSelected(false);
       male.setSelected(false);
       male.setEnabled(false);
       female.setEnabled(false);
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jDialog3WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog3WindowOpened
JOptionPane.showMessageDialog(null,"PLEASE ENTER CUSTOMER`S USERNAME AND PRESS ENTER TO CONTINUE UPDATING");        // TODO add your handling code here:
    }//GEN-LAST:event_jDialog3WindowOpened

    private void untfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_untfActionPerformed
String un=untf.getText();     
    if(un.equals("")) {
        JOptionPane.showMessageDialog(null,  "INVALID USERNAME","Error",JOptionPane.ERROR_MESSAGE);
    }
    else{
        try{
        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
        Statement stmt = con.createStatement();
        String sql="select * from customers where UserName='"+un+"' ;";
        ResultSet rs = stmt.executeQuery(sql);
        Boolean rec = rs.next();
        Statement stmt1 = con.createStatement();
        String sql1="select * from customers;";
        ResultSet rs1 = stmt1.executeQuery(sql);
        Boolean rec1 = rs1.next();
        if (!rec1) {
            JOptionPane.showMessageDialog(null,  "INVALID USERNAME","Error",JOptionPane.ERROR_MESSAGE);
            }
        else{
        if (!rec) {
            JOptionPane.showMessageDialog(null,  "INVALID USERNAME","Error",JOptionPane.ERROR_MESSAGE);
            }
       else{
       String fn=rs.getString(1);
       String ln=rs.getString(2);
       String em=rs.getString(3);
       String ph=rs.getString(4);
       String usn=rs.getString(5);
       String pc=rs.getString(6);
       String gn=rs.getString(7);
       String st=rs.getString(8);
       String ct=rs.getString(9);
       String ps=rs.getString(10);
       Date db=rs.getDate(11);  
       String ad=rs.getString(12);   
       if(gn.equals("M")){
       male.setSelected(true);
       }
       else{
       female.setSelected(true);   
       }
       jpt1.setText(fn);
       jpt2.setText(ln);
       jpt3.setText(em);
       jpt4.setText(ph);
       jpt6.setText(pc);
       jpt7.setText(ct);
       jpt8.setText(ps);
       dc1.setDate(db);       
       jpt9.setText(ad);
       jcb1.setSelectedItem(st);
       untf.setEnabled(false);
       jpt1.setEnabled(true);
       jpt2.setEnabled(true);
       jpt3.setEnabled(true);
       jpt4.setEnabled(true);
       jpt6.setEnabled(true);
       jpt7.setEnabled(true);
       jpt8.setEnabled(true);
       dc1.setEnabled(true);       
       jpt9.setEnabled(true);
       jButton5.setEnabled(true);
       jcb1.setEnabled(true);
       male.setEnabled(true);
       female.setEnabled(true);
        }
        }
    }
    catch(Exception e){
     JOptionPane.showMessageDialog(null, e.getMessage());   
    }
    }
// TODO add your handling code here:
    }//GEN-LAST:event_untfActionPerformed

    private void jDialog3WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog3WindowClosed
jpt1.setText("");
       jpt2.setText("");
       jpt3.setText("");
       jpt4.setText("");
       jpt6.setText("");
       jpt7.setText("");
       jpt8.setText("");
       dc1.setCalendar(null);
       untf.setText("" );
       jpt9.setText("");
       jcb1.setSelectedIndex(-1);
       untf.setEnabled(true);
       jpt1.setEnabled(false);
       jpt2.setEnabled(false);
       jpt3.setEnabled(false);
       jpt4.setEnabled(false);
       jpt6.setEnabled(false);
       jpt7.setEnabled(false);
       jpt8.setEnabled(false);
       dc1.setEnabled(false);       
       jpt9.setEnabled(false);
       jButton5.setEnabled(false);
       jcb1.setEnabled(false);
       male.setSelected(false);
       male.setSelected(false);
       male.setEnabled(false);
       female.setEnabled(false);     
    }//GEN-LAST:event_jDialog3WindowClosed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        new Agent_page(name1).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jlbl.setText(name1);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customermanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customermanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customermanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customermanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customermanagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_lbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable c1;
    private com.toedter.calendar.JDateChooser dc1;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel footer_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JLabel jlbl;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlbl2;
    private javax.swing.JLabel jlbl3;
    private javax.swing.JTextField jpt1;
    private javax.swing.JTextField jpt2;
    private javax.swing.JTextField jpt3;
    private javax.swing.JTextField jpt4;
    private javax.swing.JTextField jpt6;
    private javax.swing.JTextField jpt7;
    private javax.swing.JPasswordField jpt8;
    private javax.swing.JTextArea jpt9;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField untf;
    // End of variables declaration//GEN-END:variables
}
