import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sourabh
 */
public class login1 extends javax.swing.JFrame {
int i;
Timer t;
    /**
     * Creates new form login1
     */
    public login1() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        reference_caps = new javax.swing.JLabel();
        caps1 = new javax.swing.JButton();
        caps = new javax.swing.JLabel();
        pb1 = new javax.swing.JProgressBar();
        login_details_pnl = new javax.swing.JPanel();
        show = new javax.swing.JButton();
        UN = new javax.swing.JLabel();
        PAS = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ID = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        background_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHOPIFY MOBILES");
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(1366, 725));
        setMinimumSize(new java.awt.Dimension(1366, 725));
        setPreferredSize(new java.awt.Dimension(1366, 725));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layer.setMaximumSize(new java.awt.Dimension(1366, 725));
        layer.setMinimumSize(new java.awt.Dimension(1366, 725));
        layer.setPreferredSize(new java.awt.Dimension(1366, 725));
        layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading.gif"))); // NOI18N
        jLabel9.setText("PROCESSING AND VERIFYING DETAILS...");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 540, 540));

        layer.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -60, 540, 1020));

        getContentPane().add(layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1390, -1));

        reference_caps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reference_caps.setForeground(new java.awt.Color(235, 222, 17));
        reference_caps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics-exclamation-mark-939991.gif"))); // NOI18N
        getContentPane().add(reference_caps, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 60));

        caps1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics-exclamation-mark-939991.gif"))); // NOI18N
        caps1.setToolTipText("TURN CAPS LOCK OFF ");
        caps1.setContentAreaFilled(false);
        caps1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        caps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caps1ActionPerformed(evt);
            }
        });
        getContentPane().add(caps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, 200, 40));

        caps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        caps.setForeground(new java.awt.Color(235, 222, 17));
        getContentPane().add(caps, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 160, 20));

        pb1.setBackground(new java.awt.Color(30, 172, 219));
        pb1.setForeground(new java.awt.Color(0, 0, 0));
        pb1.setBorderPainted(false);
        getContentPane().add(pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1910, 20));

        login_details_pnl.setOpaque(false);
        login_details_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        show.setText("SHOW");
        show.setBorder(null);
        show.setBorderPainted(false);
        show.setContentAreaFilled(false);
        show.setMargin(null);
        show.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        show.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        login_details_pnl.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 116, 50, 20));

        UN.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        UN.setForeground(new java.awt.Color(255, 255, 255));
        UN.setText("<html><font face=\"Californian FB\" size=\"5\">User Name</font></html>");
        login_details_pnl.add(UN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        PAS.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        PAS.setForeground(new java.awt.Color(255, 255, 255));
        PAS.setText("<html><font face=\"Californian FB\" size=\"5\">Password</font></html>");
        login_details_pnl.add(PAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        login_btn.setBackground(new java.awt.Color(19, 19, 19));
        login_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        login_btn.setForeground(new java.awt.Color(204, 204, 204));
        login_btn.setText("Login");
        login_btn.setMultiClickThreshhold(2000L);
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        login_details_pnl.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 154, 120, 60));

        jButton2.setBackground(new java.awt.Color(19, 19, 19));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        login_details_pnl.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, 120, 60));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        login_details_pnl.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 43, 380, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        login_details_pnl.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 115, 380, -1));

        getContentPane().add(login_details_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 540, 250));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" Copyright © SASOFTECH TECHNOLOGY SOLUTIONS. All rights reserved.");
        jLabel6.setMaximumSize(new java.awt.Dimension(1366, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(1366, 17));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(1366, 17));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1366, 40));

        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup.png"))); // NOI18N
        signup.setBorder(null);
        signup.setContentAreaFilled(false);
        signup.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        signup.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/signup_highlight.png"))); // NOI18N
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, -20, 390, 180));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -20, 390, 180));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                            shopping  habits  sorted  out  .....");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 490, 70));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 27)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(233, 232, 232));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head6.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 1120, 50));

        ID.setBackground(new java.awt.Color(245, 249, 251));
        ID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log1.png"))); // NOI18N
        ID.setToolTipText("LOGIN");
        ID.setBorder(null);
        ID.setBorderPainted(false);
        ID.setContentAreaFilled(false);
        ID.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/log2.png"))); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 520, 230));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(233, 232, 232));
        jLabel8.setText("NEW TO SHOPIFY......");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 430, 90));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("CUSTOMER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home1.png"))); // NOI18N
        jButton6.setToolTipText("HOME");
        jButton6.setContentAreaFilled(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/home2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main.png"))); // NOI18N
        back_btn.setToolTipText("PREVIOUS PAGE");
        back_btn.setContentAreaFilled(false);
        back_btn.setHideActionText(true);
        back_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/back_main_glow.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 120, 90));

        background_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        background_lbl.setMaximumSize(new java.awt.Dimension(1366, 725));
        background_lbl.setMinimumSize(new java.awt.Dimension(1366, 725));
        background_lbl.setPreferredSize(new java.awt.Dimension(1366, 725));
        getContentPane().add(background_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
pb1.setVisible(false);    
new login1().setPreferredSize(new Dimension(1366,725));
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        layer.setVisible(false);
        UN.setVisible(false);
        reference_caps.setVisible(false);
        PAS.setVisible(false);
        caps.setVisible(false);
        username.setVisible(false);
        password.setVisible(false);
        login_btn.setVisible(false);
        background_lbl.setVisible(true);
        jButton2.setVisible(false);
        ID.setVisible(true);
        caps1.setVisible(false);
        login_details_pnl.setVisible(false);    
    }//GEN-LAST:event_formWindowOpened

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
//        login_btn.setEnabled(false);
        try{    
            int flag=0;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
            String sql="Select username,password from customers;";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(sql);
            final String log=username.getText().toLowerCase();
            String pass =new String(password.getPassword());
//            password.setText("***************************************************************************");
            while(rs.next())
            {
                if(log.equalsIgnoreCase(rs.getString(1)) && pass.equals(rs.getString(2)))
                {
                    flag=1;
                    break;
                }
            }
            if(flag==1)
            {   
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobilesr","root","opjs");
                    String sql2="insert into login1 values('"+log+"',curdate(),curtime());";
                    Statement stmt2=con.createStatement();
                    stmt2.executeUpdate(sql2);  
                }
                 catch(Exception e){
                     JOptionPane.showMessageDialog(null,e.getMessage());
                 }
                i=0;
                layer.setVisible(true);
                layer.setBackground(new Color(0, 0, 0, 150));  
                t=new Timer(50,new ActionListener(){
                    public void actionPerformed(ActionEvent e){
                        i++;
                        if(i>60){
                            jLabel9.setText("LOGGING IN AS CUSTOMER...");
                        }
                        if(i>120){
                            t.stop();
                            new categories2(log).setVisible(true);
                            dispose();
                        }
                    }
                });
                t.start();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error", "Please check user name / password",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
         
    }//GEN-LAST:event_login_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        caps1.setVisible(false);
        UN.setVisible(false);
        caps.setVisible(false);
        PAS.setVisible(false);
        username.setVisible(false);
        password.setVisible(false);
        login_btn.setVisible(false);
        jButton2.setVisible(false);
        ID.setVisible(true);
        background_lbl.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        //CAPS LOCK LABEL UPDATION STARTS HERE
        caps.setVisible(true);
        caps1.setVisible(true);
        Thread t = new Thread(new Runnable(){
            private int counter = 0;
            public void run() {
                while (true){
                    counter++;
                    SwingUtilities.invokeLater(new Runnable(){
                        public void run() {
                                boolean isOn = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
                                 if(isOn==true){ 
                                     caps1.setIcon(reference_caps.getIcon());
                                     caps.setText("CAPS LOCK IS ON");
                                 }
                                 else if(isOn==false){
                                     caps1.setIcon(null);
                                     caps.setText("");         
                                 }
                        }
                    });
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        t.start();
        //CAPS LOCK LABEL UPDATION ENDS HERE
        
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("login.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        }
        catch(IOException | LineUnavailableException | UnsupportedAudioFileException ex){
            System.out.println("Error with playing sound.");
        }
        UN.setVisible(true);
        PAS.setVisible(true);
        username.setVisible(true);
        password.setVisible(true);
        login_btn.setVisible(true);
        jButton2.setVisible(true);
        ID.setVisible(false);
        login_details_pnl.setVisible(true);
        background_lbl.setVisible(true);
    }//GEN-LAST:event_IDActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
      i=0;
        pb1.setVisible(true);
        t=new Timer(2,new ActionListener(){
            public void actionPerformed(ActionEvent e){
                pb1.setValue(i);
                i++;
                if(i>100){
                    t.stop();
                    new signup().setVisible(true);
                    dispose();
                }
            }
        });

        t.start();        
    }//GEN-LAST:event_signupActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        new index().setVisible(true);        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        dispose();
        new login_options().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        login_btn.doClick();
    }//GEN-LAST:event_passwordActionPerformed

    private void caps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caps1ActionPerformed
        Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK, false);
    }//GEN-LAST:event_caps1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        login_btn.doClick();
    }//GEN-LAST:event_usernameActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if(show.getText().equals("SHOW")){
        password.setEchoChar((char)0);
        show.setText("HIDE");
        show.setForeground(new Color(38,85,116));
        }
        else if(show.getText().equals("HIDE")){
        password.setEchoChar('*');
        show.setText("SHOW");
        show.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_showActionPerformed

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
         if(password.getText().length()>31&&!(evt.getKeyChar()==KeyEvent.VK_ENTER||evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"PASSWORD SHOULD BE LESS THAN 32 CHARACTERS","ERROR",JOptionPane.WARNING_MESSAGE);
            evt.consume();
         }
    }//GEN-LAST:event_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ID;
    private javax.swing.JLabel PAS;
    private javax.swing.JLabel UN;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel background_lbl;
    private javax.swing.JLabel caps;
    private javax.swing.JButton caps1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel layer;
    private javax.swing.JButton login_btn;
    private javax.swing.JPanel login_details_pnl;
    private javax.swing.JPasswordField password;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JLabel reference_caps;
    private javax.swing.JButton show;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
